
// utils/itemsSeleccionados27bloques.js

const  itemsSeleccionados = [
  
  { id: 'T2_2H_BOW', nombre: 'T2 2H Bow' },
  { id: 'T2_2H_TOOL_AXE', nombre: 'T2 2H Tool Axe' },
  { id: 'T2_2H_TOOL_HAMMER', nombre: 'T2 2H Tool Hammer' },
  { id: 'T2_2H_TOOL_KNIFE', nombre: 'T2 2H Tool Knife' },
  { id: 'T2_2H_TOOL_PICK', nombre: 'T2 2H Tool Pick' },
  { id: 'T2_2H_TOOL_SICKLE', nombre: 'T2 2H Tool Sickle' },
  { id: 'T2_2H_TOOL_SIEGEHAMMER', nombre: 'T2 2H Tool Siegehammer' },
  { id: 'T2_ARMOR_CLOTH_SET1', nombre: 'T2 Armor Cloth Set1' },
  { id: 'T2_ARMOR_LEATHER_SET1', nombre: 'T2 Armor Leather Set1' },
  { id: 'T2_ARMOR_PLATE_SET1', nombre: 'T2 Armor Plate Set1' },
  { id: 'T2_BAG', nombre: 'T2 Bag' },
  { id: 'T2_CAPE', nombre: 'T2 Cape' },
  { id: 'T2_HEAD_CLOTH_SET1', nombre: 'T2 Head Cloth Set1' },
  { id: 'T2_HEAD_LEATHER_SET1', nombre: 'T2 Head Leather Set1' },
  { id: 'T2_HEAD_PLATE_SET1', nombre: 'T2 Head Plate Set1' },
  { id: 'T2_MAIN_FIRESTAFF', nombre: 'T2 Main Firestaff' },
  { id: 'T2_OFF_BOOK', nombre: 'T2 Off Book' },
  { id: 'T2_OFF_SHIELD', nombre: 'T2 Off Shield' },
  { id: 'T2_SHOES_CLOTH_SET1', nombre: 'T2 Shoes Cloth Set1' },
  { id: 'T2_SHOES_LEATHER_SET1', nombre: 'T2 Shoes Leather Set1' },
  { id: 'T2_SHOES_PLATE_SET1', nombre: 'T2 Shoes Plate Set1' },
  { id: 'T3_2H_BOW', nombre: 'T3 2H Bow' },
  { id: 'T3_2H_CROSSBOW', nombre: 'T3 2H Crossbow' },
  { id: 'T3_2H_KNUCKLES_SET1', nombre: 'T3 2H Knuckles Set1' },
  { id: 'T3_2H_QUARTERSTAFF', nombre: 'T3 2H Quarterstaff' },
  { id: 'T3_2H_SHAPESHIFTER_SET1', nombre: 'T3 2H Shapeshifter Set1' },
  { id: 'T3_2H_TOOL_AXE', nombre: 'T3 2H Tool Axe' },
  { id: 'T3_2H_TOOL_FISHINGROD', nombre: 'T3 2H Tool Fishingrod' },
  { id: 'T3_2H_TOOL_HAMMER', nombre: 'T3 2H Tool Hammer' },
  { id: 'T3_2H_TOOL_KNIFE', nombre: 'T3 2H Tool Knife' },
  { id: 'T3_2H_TOOL_PICK', nombre: 'T3 2H Tool Pick' },
  { id: 'T3_2H_TOOL_SICKLE', nombre: 'T3 2H Tool Sickle' },
  { id: 'T3_2H_TOOL_SIEGEHAMMER', nombre: 'T3 2H Tool Siegehammer' },
  { id: 'T3_2H_TOOL_TRACKING', nombre: 'T3 2H Tool Tracking' },
  { id: 'T3_ARMOR_CLOTH_SET1', nombre: 'T3 Armor Cloth Set1' },
  { id: 'T3_ARMOR_LEATHER_SET1', nombre: 'T3 Armor Leather Set1' },
  { id: 'T3_ARMOR_PLATE_SET1', nombre: 'T3 Armor Plate Set1' },
  { id: 'T3_BAG', nombre: 'T3 Bag' },
  { id: 'T3_CAPE', nombre: 'T3 Cape' },
  { id: 'T3_HEAD_CLOTH_SET1', nombre: 'T3 Head Cloth Set1' },
  { id: 'T3_HEAD_LEATHER_SET1', nombre: 'T3 Head Leather Set1' },
  { id: 'T3_HEAD_PLATE_SET1', nombre: 'T3 Head Plate Set1' },
  { id: 'T3_MAIN_ARCANESTAFF', nombre: 'T3 Main Arcanestaff' },
  { id: 'T3_MAIN_AXE', nombre: 'T3 Main Axe' },
  { id: 'T3_MAIN_CURSEDSTAFF', nombre: 'T3 Main Cursedstaff' },
  { id: 'T3_MAIN_DAGGER', nombre: 'T3 Main Dagger' },
  { id: 'T3_MAIN_FIRESTAFF', nombre: 'T3 Main Firestaff' },
  { id: 'T3_MAIN_HAMMER', nombre: 'T3 Main Hammer' },
  { id: 'T3_MAIN_HOLYSTAFF', nombre: 'T3 Main Holystaff' },
  { id: 'T3_MAIN_MACE', nombre: 'T3 Main Mace' },
  { id: 'T3_MAIN_NATURESTAFF', nombre: 'T3 Main Naturestaff' },
  { id: 'T3_MAIN_SPEAR', nombre: 'T3 Main Spear' },
  { id: 'T3_MAIN_SWORD', nombre: 'T3 Main Sword' },
  { id: 'T3_OFF_BOOK', nombre: 'T3 Off Book' },
  { id: 'T3_OFF_HORN', nombre: 'T3 Off Horn' },
  { id: 'T3_OFF_ORB', nombre: 'T3 Off Orb' },
  { id: 'T3_OFF_SHIELD', nombre: 'T3 Off Shield' },
  { id: 'T3_OFF_SPIKEDSHIELD', nombre: 'T3 Off Spikedshield' },
  { id: 'T3_OFF_TOWERSHIELD', nombre: 'T3 Off Towershield' },
  { id: 'T3_SHOES_CLOTH_SET1', nombre: 'T3 Shoes Cloth Set1' },
  { id: 'T3_SHOES_LEATHER_SET1', nombre: 'T3 Shoes Leather Set1' },
  { id: 'T3_SHOES_PLATE_SET1', nombre: 'T3 Shoes Plate Set1' },
  { id: 'T4_2H_ARCANESTAFF', nombre: 'T4 2H Arcanestaff' },
  { id: 'T4_2H_AXE', nombre: 'T4 2H Axe' },
  { id: 'T4_2H_BOW', nombre: 'T4 2H Bow' },
  { id: 'T4_2H_CLAYMORE', nombre: 'T4 2H Claymore' },
  { id: 'T4_2H_CROSSBOW', nombre: 'T4 2H Crossbow' },
  { id: 'T4_2H_CURSEDSTAFF', nombre: 'T4 2H Cursedstaff' },
  { id: 'T4_2H_DAGGERPAIR', nombre: 'T4 2H Daggerpair' },
  { id: 'T4_2H_FIRESTAFF', nombre: 'T4 2H Firestaff' },
  { id: 'T4_2H_GLAIVE', nombre: 'T4 2H Glaive' },
  { id: 'T4_2H_HALBERD', nombre: 'T4 2H Halberd' },
  { id: 'T4_2H_HAMMER', nombre: 'T4 2H Hammer' },
  { id: 'T4_2H_HOLYSTAFF', nombre: 'T4 2H Holystaff' },
  { id: 'T4_2H_KNUCKLES_SET1', nombre: 'T4 2H Knuckles Set1' },
  { id: 'T4_2H_MACE', nombre: 'T4 2H Mace' },
  { id: 'T4_2H_NATURESTAFF', nombre: 'T4 2H Naturestaff' },
  { id: 'T4_2H_QUARTERSTAFF', nombre: 'T4 2H Quarterstaff' },
  { id: 'T4_2H_SCYTHE', nombre: 'T4 2H Scythe' },
  { id: 'T4_2H_SHAPESHIFTER_SET1', nombre: 'T4 2H Shapeshifter Set1' },
  { id: 'T4_2H_SPEAR', nombre: 'T4 2H Spear' },
  { id: 'T4_2H_TOOL_AXE', nombre: 'T4 2H Tool Axe' },
  { id: 'T4_2H_TOOL_FISHINGROD', nombre: 'T4 2H Tool Fishingrod' },
  { id: 'T4_2H_TOOL_HAMMER', nombre: 'T4 2H Tool Hammer' },
  { id: 'T4_2H_TOOL_KNIFE', nombre: 'T4 2H Tool Knife' },
  { id: 'T4_2H_TOOL_PICK', nombre: 'T4 2H Tool Pick' },
  { id: 'T4_2H_TOOL_SICKLE', nombre: 'T4 2H Tool Sickle' },
  { id: 'T4_2H_TOOL_SIEGEHAMMER', nombre: 'T4 2H Tool Siegehammer' },
  { id: 'T4_2H_TOOL_TRACKING', nombre: 'T4 2H Tool Tracking' },
  { id: 'T4_ARMOR_CLOTH_SET1', nombre: 'T4 Armor Cloth Set1' },
  { id: 'T4_ARMOR_LEATHER_SET1', nombre: 'T4 Armor Leather Set1' },
  { id: 'T4_ARMOR_PLATE_SET1', nombre: 'T4 Armor Plate Set1' },
  { id: 'T4_BAG', nombre: 'T4 Bag' },
  { id: 'T4_CAPE', nombre: 'T4 Cape' },
  { id: 'T4_HEAD_CLOTH_SET1', nombre: 'T4 Head Cloth Set1' },
  { id: 'T4_HEAD_LEATHER_SET1', nombre: 'T4 Head Leather Set1' },
  { id: 'T4_HEAD_PLATE_SET1', nombre: 'T4 Head Plate Set1' },
  { id: 'T4_MAIN_ARCANESTAFF', nombre: 'T4 Main Arcanestaff' },
  { id: 'T4_MAIN_AXE', nombre: 'T4 Main Axe' },
  { id: 'T4_MAIN_CURSEDSTAFF', nombre: 'T4 Main Cursedstaff' },
  { id: 'T4_MAIN_DAGGER', nombre: 'T4 Main Dagger' },
  { id: 'T4_MAIN_FIRESTAFF', nombre: 'T4 Main Firestaff' },
  { id: 'T4_MAIN_HOLYSTAFF', nombre: 'T4 Main Holystaff' },
  { id: 'T4_MAIN_MACE', nombre: 'T4 Main Mace' },
  { id: 'T4_MAIN_NATURESTAFF', nombre: 'T4 Main Naturestaff' },
  { id: 'T4_MAIN_SPEAR', nombre: 'T4 Main Spear' },
  { id: 'T4_MAIN_SWORD', nombre: 'T4 Main Sword' },
  { id: 'T4_OFF_BOOK', nombre: 'T4 Off Book' },
  { id: 'T4_OFF_HORN', nombre: 'T4 Off Horn' },
  { id: 'T4_OFF_ORB', nombre: 'T4 Off Orb' },
  { id: 'T4_OFF_SHIELD', nombre: 'T4 Off Shield' },
  { id: 'T4_OFF_SPIKEDSHIELD', nombre: 'T4 Off Spikedshield' },
  { id: 'T4_OFF_TOWERSHIELD', nombre: 'T4 Off Towershield' },
  { id: 'T4_SHOES_CLOTH_SET1', nombre: 'T4 Shoes Cloth Set1' },
  { id: 'T4_SHOES_LEATHER_SET1', nombre: 'T4 Shoes Leather Set1' },
  { id: 'T4_SHOES_PLATE_SET1', nombre: 'T4 Shoes Plate Set1' },
  { id: 'T5_2H_ARCANESTAFF', nombre: 'T5 2H Arcanestaff' },
  { id: 'T5_2H_AXE', nombre: 'T5 2H Axe' },
  { id: 'T5_2H_BOW', nombre: 'T5 2H Bow' },
  { id: 'T5_2H_CLAYMORE', nombre: 'T5 2H Claymore' },
  { id: 'T5_2H_CROSSBOW', nombre: 'T5 2H Crossbow' },
  { id: 'T5_2H_CURSEDSTAFF', nombre: 'T5 2H Cursedstaff' },
  { id: 'T5_2H_DAGGERPAIR', nombre: 'T5 2H Daggerpair' },
  { id: 'T5_2H_FIRESTAFF', nombre: 'T5 2H Firestaff' },
  { id: 'T5_2H_GLAIVE', nombre: 'T5 2H Glaive' },
  { id: 'T5_2H_HALBERD', nombre: 'T5 2H Halberd' },
  { id: 'T5_2H_HAMMER', nombre: 'T5 2H Hammer' },
  { id: 'T5_2H_HOLYSTAFF', nombre: 'T5 2H Holystaff' },
  { id: 'T5_2H_KNUCKLES_SET1', nombre: 'T5 2H Knuckles Set1' },
  { id: 'T5_2H_MACE', nombre: 'T5 2H Mace' },
  { id: 'T5_2H_NATURESTAFF', nombre: 'T5 2H Naturestaff' },
  { id: 'T5_2H_QUARTERSTAFF', nombre: 'T5 2H Quarterstaff' },
  { id: 'T5_2H_SCYTHE', nombre: 'T5 2H Scythe' },
  { id: 'T5_2H_SHAPESHIFTER_SET1', nombre: 'T5 2H Shapeshifter Set1' },
  { id: 'T5_2H_SPEAR', nombre: 'T5 2H Spear' },
  { id: 'T5_2H_TOOL_AXE', nombre: 'T5 2H Tool Axe' },
  { id: 'T5_2H_TOOL_FISHINGROD', nombre: 'T5 2H Tool Fishingrod' },
  { id: 'T5_2H_TOOL_HAMMER', nombre: 'T5 2H Tool Hammer' },
  { id: 'T5_2H_TOOL_KNIFE', nombre: 'T5 2H Tool Knife' },
  { id: 'T5_2H_TOOL_PICK', nombre: 'T5 2H Tool Pick' },
  { id: 'T5_2H_TOOL_SICKLE', nombre: 'T5 2H Tool Sickle' },
  { id: 'T5_2H_TOOL_SIEGEHAMMER', nombre: 'T5 2H Tool Siegehammer' },
  { id: 'T5_2H_TOOL_TRACKING', nombre: 'T5 2H Tool Tracking' },
  { id: 'T5_ARMOR_CLOTH_SET1', nombre: 'T5 Armor Cloth Set1' },
  { id: 'T5_ARMOR_LEATHER_SET1', nombre: 'T5 Armor Leather Set1' },
  { id: 'T5_ARMOR_PLATE_SET1', nombre: 'T5 Armor Plate Set1' },
  { id: 'T5_BAG', nombre: 'T5 Bag' },
  { id: 'T5_CAPE', nombre: 'T5 Cape' },
  { id: 'T5_HEAD_CLOTH_SET1', nombre: 'T5 Head Cloth Set1' },
  { id: 'T5_HEAD_LEATHER_SET1', nombre: 'T5 Head Leather Set1' },
  { id: 'T5_HEAD_PLATE_SET1', nombre: 'T5 Head Plate Set1' },
  { id: 'T5_MAIN_ARCANESTAFF', nombre: 'T5 Main Arcanestaff' },
  { id: 'T5_MAIN_AXE', nombre: 'T5 Main Axe' },
  { id: 'T5_MAIN_BOW', nombre: 'T5 Main Bow' },
  { id: 'T5_MAIN_CROSSBOW', nombre: 'T5 Main Crossbow' },
  { id: 'T5_MAIN_CURSEDSTAFF', nombre: 'T5 Main Cursedstaff' },
  { id: 'T5_MAIN_DAGGER', nombre: 'T5 Main Dagger' },
  { id: 'T5_MAIN_FIRESTAFF', nombre: 'T5 Main Firestaff' },
  { id: 'T5_MAIN_HOLYSTAFF', nombre: 'T5 Main Holystaff' },
  { id: 'T5_MAIN_MACE', nombre: 'T5 Main Mace' },
  { id: 'T5_MAIN_NATURESTAFF', nombre: 'T5 Main Naturestaff' },
  { id: 'T5_MAIN_SPEAR', nombre: 'T5 Main Spear' },
  { id: 'T5_MAIN_SWORD', nombre: 'T5 Main Sword' },
  { id: 'T5_OFF_BOOK', nombre: 'T5 Off Book' },
  { id: 'T5_OFF_HORN', nombre: 'T5 Off Horn' },
  { id: 'T5_OFF_ORB', nombre: 'T5 Off Orb' },
  { id: 'T5_OFF_SHIELD', nombre: 'T5 Off Shield' },
  { id: 'T5_OFF_SPIKEDSHIELD', nombre: 'T5 Off Spikedshield' },
  { id: 'T5_OFF_TOWERSHIELD', nombre: 'T5 Off Towershield' },
  { id: 'T5_SHOES_CLOTH_SET1', nombre: 'T5 Shoes Cloth Set1' },
  { id: 'T5_SHOES_LEATHER_SET1', nombre: 'T5 Shoes Leather Set1' },
  { id: 'T5_SHOES_PLATE_SET1', nombre: 'T5 Shoes Plate Set1' },
  { id: 'T6_2H_ARCANESTAFF', nombre: 'T6 2H Arcanestaff' },
  { id: 'T6_2H_AXE', nombre: 'T6 2H Axe' },
  { id: 'T6_2H_BOW', nombre: 'T6 2H Bow' },
  { id: 'T6_2H_CLAYMORE', nombre: 'T6 2H Claymore' },
  { id: 'T6_2H_CROSSBOW', nombre: 'T6 2H Crossbow' },
  { id: 'T6_2H_CURSEDSTAFF', nombre: 'T6 2H Cursedstaff' },
  { id: 'T6_2H_DAGGERPAIR', nombre: 'T6 2H Daggerpair' },
  { id: 'T6_2H_FIRESTAFF', nombre: 'T6 2H Firestaff' },
  { id: 'T6_2H_GLAIVE', nombre: 'T6 2H Glaive' },
  { id: 'T6_2H_HALBERD', nombre: 'T6 2H Halberd' },
  { id: 'T6_2H_HAMMER', nombre: 'T6 2H Hammer' },
  { id: 'T6_2H_HOLYSTAFF', nombre: 'T6 2H Holystaff' },
  { id: 'T6_2H_KNUCKLES_SET1', nombre: 'T6 2H Knuckles Set1' },
  { id: 'T6_2H_MACE', nombre: 'T6 2H Mace' },
  { id: 'T6_2H_NATURESTAFF', nombre: 'T6 2H Naturestaff' },
  { id: 'T6_2H_QUARTERSTAFF', nombre: 'T6 2H Quarterstaff' },
  { id: 'T6_2H_SCYTHE', nombre: 'T6 2H Scythe' },
  { id: 'T6_2H_SHAPESHIFTER_SET1', nombre: 'T6 2H Shapeshifter Set1' },
  { id: 'T6_2H_SPEAR', nombre: 'T6 2H Spear' },
  { id: 'T6_2H_TOOL_AXE', nombre: 'T6 2H Tool Axe' },
  { id: 'T6_2H_TOOL_FISHINGROD', nombre: 'T6 2H Tool Fishingrod' },
  { id: 'T6_2H_TOOL_HAMMER', nombre: 'T6 2H Tool Hammer' },
  { id: 'T6_2H_TOOL_KNIFE', nombre: 'T6 2H Tool Knife' },
  { id: 'T6_2H_TOOL_PICK', nombre: 'T6 2H Tool Pick' },
  { id: 'T6_2H_TOOL_SICKLE', nombre: 'T6 2H Tool Sickle' },
  { id: 'T6_2H_TOOL_SKNIFE', nombre: 'T6 2H Tool Sknife' },
  { id: 'T6_2H_TRIDENT', nombre: 'T6 2H Trident' },
  { id: 'T6_2H_TWINSCYTHE', nombre: 'T6 2H Twinscythe' },
  { id: 'T6_2H_WARBOW', nombre: 'T6 2H Warbow' },
  { id: 'T6_ARMOR_CLOTH_SET1', nombre: 'T6 Armor Cloth Set1' },
  { id: 'T6_ARMOR_LEATHER_SET1', nombre: 'T6 Armor Leather Set1' },
  { id: 'T6_ARMOR_PLATE_SET1', nombre: 'T6 Armor Plate Set1' },
  { id: 'T6_BAG', nombre: 'T6 Bag' },
  { id: 'T6_CAPE', nombre: 'T6 Cape' },
  { id: 'T6_HEAD_CLOTH_SET1', nombre: 'T6 Head Cloth Set1' },
  { id: 'T6_HEAD_LEATHER_SET1', nombre: 'T6 Head Leather Set1' },
  { id: 'T6_HEAD_PLATE_SET1', nombre: 'T6 Head Plate Set1' },
  { id: 'T6_MAIN_ARCANESTAFF', nombre: 'T6 Main Arcanestaff' },
  { id: 'T6_MAIN_AXE', nombre: 'T6 Main Axe' },
  { id: 'T6_MAIN_BOW', nombre: 'T6 Main Bow' },
  { id: 'T6_MAIN_CROSSBOW', nombre: 'T6 Main Crossbow' },
  { id: 'T6_MAIN_CURSEDSTAFF', nombre: 'T6 Main Cursedstaff' },
  { id: 'T6_MAIN_DAGGER', nombre: 'T6 Main Dagger' },
  { id: 'T6_MAIN_FIRESTAFF', nombre: 'T6 Main Firestaff' },
  { id: 'T6_MAIN_HOLYSTAFF', nombre: 'T6 Main Holystaff' },
  { id: 'T6_MAIN_MACE', nombre: 'T6 Main Mace' },
  { id: 'T6_MAIN_NATURESTAFF', nombre: 'T6 Main Naturestaff' },
  { id: 'T6_MAIN_SPEAR', nombre: 'T6 Main Spear' },
  { id: 'T6_MAIN_SWORD', nombre: 'T6 Main Sword' },
  { id: 'T6_OFF_BOOK', nombre: 'T6 Off Book' },
  { id: 'T6_OFF_HORN', nombre: 'T6 Off Horn' },
  { id: 'T6_OFF_ORB', nombre: 'T6 Off Orb' },
  { id: 'T6_OFF_SHIELD', nombre: 'T6 Off Shield' },
  { id: 'T6_OFF_SPIKEDSHIELD', nombre: 'T6 Off Spikedshield' },
  { id: 'T6_OFF_TOWERSHIELD', nombre: 'T6 Off Towershield' },
  { id: 'T6_SHOES_CLOTH_SET1', nombre: 'T6 Shoes Cloth Set1' },
  { id: 'T6_SHOES_LEATHER_SET1', nombre: 'T6 Shoes Leather Set1' },
  { id: 'T6_SHOES_PLATE_SET1', nombre: 'T6 Shoes Plate Set1' },
  { id: 'T7_2H_ARCANESTAFF', nombre: 'T7 2H Arcanestaff' },
  { id: 'T7_2H_AXE', nombre: 'T7 2H Axe' },
  { id: 'T7_2H_BOW', nombre: 'T7 2H Bow' },
  { id: 'T7_2H_CLAYMORE', nombre: 'T7 2H Claymore' },
  { id: 'T7_2H_CROSSBOW', nombre: 'T7 2H Crossbow' },
  { id: 'T7_2H_CURSEDSTAFF', nombre: 'T7 2H Cursedstaff' },
  { id: 'T7_2H_DAGGERPAIR', nombre: 'T7 2H Daggerpair' },
  { id: 'T7_2H_FIRESTAFF', nombre: 'T7 2H Firestaff' },
  { id: 'T7_2H_GLAIVE', nombre: 'T7 2H Glaive' },
  { id: 'T7_2H_HALBERD', nombre: 'T7 2H Halberd' },
  { id: 'T7_2H_HAMMER', nombre: 'T7 2H Hammer' },
  { id: 'T7_2H_HOLYSTAFF', nombre: 'T7 2H Holystaff' },
  { id: 'T7_2H_KNUCKLES_SET1', nombre: 'T7 2H Knuckles Set1' },
  { id: 'T7_2H_MACE', nombre: 'T7 2H Mace' },
  { id: 'T7_2H_NATURESTAFF', nombre: 'T7 2H Naturestaff' },
  { id: 'T7_2H_QUARTERSTAFF', nombre: 'T7 2H Quarterstaff' },
  { id: 'T7_2H_SCYTHE', nombre: 'T7 2H Scythe' },
  { id: 'T7_2H_SPEAR', nombre: 'T7 2H Spear' },
  { id: 'T7_2H_STAFF', nombre: 'T7 2H Staff' },
  { id: 'T7_2H_SWORD', nombre: 'T7 2H Sword' },
  { id: 'T7_2H_TOOL_HAMMER', nombre: 'T7 2H Tool Hammer' },
  { id: 'T7_2H_TOOL_PICK', nombre: 'T7 2H Tool Pick' },
  { id: 'T7_2H_TOOL_SAW', nombre: 'T7 2H Tool Saw' },
  { id: 'T7_2H_TOOL_SICKLE', nombre: 'T7 2H Tool Sickle' },
  { id: 'T7_2H_TOOL_SKINNER', nombre: 'T7 2H Tool Skinner' },
  { id: 'T7_2H_TOOL_SKNIFE', nombre: 'T7 2H Tool Sknife' },
  { id: 'T7_2H_TRIDENT', nombre: 'T7 2H Trident' },
  { id: 'T7_2H_TWINSCYTHE', nombre: 'T7 2H Twinscythe' },
  { id: 'T7_2H_WARBOW', nombre: 'T7 2H Warbow' },
  { id: 'T7_ARMOR_CLOTH_SET1', nombre: 'T7 Armor Cloth Set1' },
  { id: 'T7_ARMOR_LEATHER_SET1', nombre: 'T7 Armor Leather Set1' },
  { id: 'T7_ARMOR_PLATE_SET1', nombre: 'T7 Armor Plate Set1' },
  { id: 'T7_BAG', nombre: 'T7 Bag' },
  { id: 'T7_CAPE', nombre: 'T7 Cape' },
  { id: 'T7_HEAD_CLOTH_SET1', nombre: 'T7 Head Cloth Set1' },
  { id: 'T7_HEAD_LEATHER_SET1', nombre: 'T7 Head Leather Set1' },
  { id: 'T7_HEAD_PLATE_SET1', nombre: 'T7 Head Plate Set1' },
  { id: 'T7_MAIN_ARCANESTAFF', nombre: 'T7 Main Arcanestaff' },
  { id: 'T7_MAIN_AXE', nombre: 'T7 Main Axe' },
  { id: 'T7_MAIN_BOW', nombre: 'T7 Main Bow' },
  { id: 'T7_MAIN_CROSSBOW', nombre: 'T7 Main Crossbow' },
  { id: 'T7_MAIN_CURSEDSTAFF', nombre: 'T7 Main Cursedstaff' },
  { id: 'T7_MAIN_DAGGER', nombre: 'T7 Main Dagger' },
  { id: 'T7_MAIN_FIRESTAFF', nombre: 'T7 Main Firestaff' },
  { id: 'T7_MAIN_HOLYSTAFF', nombre: 'T7 Main Holystaff' },
  { id: 'T7_MAIN_MACE', nombre: 'T7 Main Mace' },
  { id: 'T7_MAIN_NATURESTAFF', nombre: 'T7 Main Naturestaff' },
  { id: 'T7_MAIN_SPEAR', nombre: 'T7 Main Spear' },
  { id: 'T7_MAIN_SWORD', nombre: 'T7 Main Sword' },
  { id: 'T7_OFF_BOOK', nombre: 'T7 Off Book' },
  { id: 'T7_OFF_HORN', nombre: 'T7 Off Horn' },
  { id: 'T7_OFF_ORB', nombre: 'T7 Off Orb' },
  { id: 'T7_OFF_SHIELD', nombre: 'T7 Off Shield' },
  { id: 'T7_OFF_SPIKEDSHIELD', nombre: 'T7 Off Spikedshield' },
  { id: 'T7_OFF_TOWERSHIELD', nombre: 'T7 Off Towershield' },
  { id: 'T7_SHOES_CLOTH_SET1', nombre: 'T7 Shoes Cloth Set1' },
  { id: 'T7_SHOES_LEATHER_SET1', nombre: 'T7 Shoes Leather Set1' },
  { id: 'T7_SHOES_PLATE_SET1', nombre: 'T7 Shoes Plate Set1' },
  { id: 'T8_2H_ARCANESTAFF', nombre: 'T8 2H Arcanestaff' },
  { id: 'T8_2H_AXE', nombre: 'T8 2H Axe' },
  { id: 'T8_2H_BOW', nombre: 'T8 2H Bow' },
  { id: 'T8_2H_CLAYMORE', nombre: 'T8 2H Claymore' },
  { id: 'T8_2H_CROSSBOW', nombre: 'T8 2H Crossbow' },
  { id: 'T8_2H_CURSEDSTAFF', nombre: 'T8 2H Cursedstaff' },
  { id: 'T8_2H_DAGGERPAIR', nombre: 'T8 2H Daggerpair' },
  { id: 'T8_2H_FIRESTAFF', nombre: 'T8 2H Firestaff' },
  { id: 'T8_2H_HOLYSTAFF', nombre: 'T8 2H Holystaff' },
  { id: 'T8_2H_MACE', nombre: 'T8 2H Mace' },
  { id: 'T8_2H_NATURESTAFF', nombre: 'T8 2H Naturestaff' },
  { id: 'T8_2H_SPEAR', nombre: 'T8 2H Spear' },
  { id: 'T8_2H_SWORD', nombre: 'T8 2H Sword' },
  { id: 'T8_2H_TOOL_HAMMER', nombre: 'T8 2H Tool Hammer' },
  { id: 'T8_2H_TOOL_PICK', nombre: 'T8 2H Tool Pick' },
  { id: 'T8_2H_TOOL_SAW', nombre: 'T8 2H Tool Saw' },
  { id: 'T8_2H_TOOL_SICKLE', nombre: 'T8 2H Tool Sickle' },
  { id: 'T8_2H_TOOL_SKINNER', nombre: 'T8 2H Tool Skinner' },
  { id: 'T8_2H_TOOL_SKNIFE', nombre: 'T8 2H Tool Sknife' },
  { id: 'T8_2H_TRIDENT', nombre: 'T8 2H Trident' },
  { id: 'T8_2H_TWINSCYTHE', nombre: 'T8 2H Twinscythe' },
  { id: 'T8_2H_WARBOW', nombre: 'T8 2H Warbow' },
  { id: 'T8_ARMOR_CLOTH_SET1', nombre: 'T8 Armor Cloth Set1' },
  { id: 'T8_ARMOR_LEATHER_SET1', nombre: 'T8 Armor Leather Set1' },
  { id: 'T8_ARMOR_PLATE_SET1', nombre: 'T8 Armor Plate Set1' },
  { id: 'T8_BAG', nombre: 'T8 Bag' },
  { id: 'T8_CAPE', nombre: 'T8 Cape' },
  { id: 'T8_HEAD_CLOTH_SET1', nombre: 'T8 Head Cloth Set1' },
  { id: 'T8_HEAD_LEATHER_SET1', nombre: 'T8 Head Leather Set1' },
  { id: 'T8_HEAD_PLATE_SET1', nombre: 'T8 Head Plate Set1' },
  { id: 'T8_MAIN_ARCANESTAFF', nombre: 'T8 Main Arcanestaff' },
  { id: 'T8_MAIN_AXE', nombre: 'T8 Main Axe' },
  { id: 'T8_MAIN_BOW', nombre: 'T8 Main Bow' },
  { id: 'T8_MAIN_CROSSBOW', nombre: 'T8 Main Crossbow' },
  { id: 'T8_MAIN_CURSEDSTAFF', nombre: 'T8 Main Cursedstaff' },
  { id: 'T8_MAIN_DAGGER', nombre: 'T8 Main Dagger' },
  { id: 'T8_MAIN_FIRESTAFF', nombre: 'T8 Main Firestaff' },
  { id: 'T8_MAIN_HOLYSTAFF', nombre: 'T8 Main Holystaff' },
  { id: 'T8_MAIN_MACE', nombre: 'T8 Main Mace' },
  { id: 'T8_MAIN_NATURESTAFF', nombre: 'T8 Main Naturestaff' },
  { id: 'T8_MAIN_SPEAR', nombre: 'T8 Main Spear' },
  { id: 'T8_MAIN_SWORD', nombre: 'T8 Main Sword' },
  { id: 'T8_OFF_BOOK', nombre: 'T8 Off Book' },
  { id: 'T8_OFF_HORN', nombre: 'T8 Off Horn' },
  { id: 'T8_OFF_ORB', nombre: 'T8 Off Orb' },
  { id: 'T8_OFF_SHIELD', nombre: 'T8 Off Shield' },
  { id: 'T8_OFF_SPIKEDSHIELD', nombre: 'T8 Off Spikedshield' },
  { id: 'T8_OFF_TOWERSHIELD', nombre: 'T8 Off Towershield' },
  { id: 'T8_SHOES_CLOTH_SET1', nombre: 'T8 Shoes Cloth Set1' },
  { id: 'T8_SHOES_LEATHER_SET1', nombre: 'T8 Shoes Leather Set1' },
  { id: 'T8_SHOES_PLATE_SET1', nombre: 'T8 Shoes Plate Set1' },
  { id: 'T9_2H_ARCANESTAFF', nombre: 'T9 2H Arcanestaff' },
  { id: 'T9_2H_BOW', nombre: 'T9 2H Bow' },
  { id: 'T9_2H_CLAYMORE', nombre: 'T9 2H Claymore' },
  { id: 'T9_2H_CROSSBOW', nombre: 'T9 2H Crossbow' },
  { id: 'T9_2H_CURSEDSTAFF', nombre: 'T9 2H Cursedstaff' },
  { id: 'T9_2H_DAGGER', nombre: 'T9 2H Dagger' },
  { id: 'T9_2H_FIRESTAFF', nombre: 'T9 2H Firestaff' },
  { id: 'T9_2H_HAMMER', nombre: 'T9 2H Hammer' },
  { id: 'T9_2H_HOLYSTAFF', nombre: 'T9 2H Holystaff' },
  { id: 'T9_2H_MACE', nombre: 'T9 2H Mace' },
  { id: 'T9_2H_NATURESTAFF', nombre: 'T9 2H Naturestaff' },
  { id: 'T9_2H_SPEAR', nombre: 'T9 2H Spear' },
  { id: 'T9_2H_SWORD', nombre: 'T9 2H Sword' },
  { id: 'T9_2H_TOOL_HAMMER', nombre: 'T9 2H Tool Hammer' },
  { id: 'T9_2H_TOOL_PICK', nombre: 'T9 2H Tool Pick' },
  { id: 'T9_2H_TOOL_SAW', nombre: 'T9 2H Tool Saw' },
  { id: 'T9_2H_TOOL_SICKLE', nombre: 'T9 2H Tool Sickle' },
  { id: 'T9_2H_TOOL_SKINNER', nombre: 'T9 2H Tool Skinner' },
  { id: 'T9_2H_TOOL_SKNIFE', nombre: 'T9 2H Tool Sknife' },
  { id: 'T9_2H_TRIDENT', nombre: 'T9 2H Trident' },
  { id: 'T9_2H_TWINSCYTHE', nombre: 'T9 2H Twinscythe' },
  { id: 'T9_2H_WARBOW', nombre: 'T9 2H Warbow' },
  { id: 'T9_ARMOR_CLOTH_SET1', nombre: 'T9 Armor Cloth Set1' },
  { id: 'T9_ARMOR_LEATHER_SET1', nombre: 'T9 Armor Leather Set1' },
  { id: 'T9_ARMOR_PLATE_SET1', nombre: 'T9 Armor Plate Set1' },
  { id: 'T9_BAG', nombre: 'T9 Bag' },
  { id: 'T9_CAPE', nombre: 'T9 Cape' },
  { id: 'T9_HEAD_CLOTH_SET1', nombre: 'T9 Head Cloth Set1' },
  { id: 'T9_HEAD_LEATHER_SET1', nombre: 'T9 Head Leather Set1' },
  { id: 'T9_HEAD_PLATE_SET1', nombre: 'T9 Head Plate Set1' },
  { id: 'T9_MAIN_ARCANESTAFF', nombre: 'T9 Main Arcanestaff' },
  { id: 'T9_MAIN_AXE', nombre: 'T9 Main Axe' },
  { id: 'T9_MAIN_BOW', nombre: 'T9 Main Bow' },
  { id: 'T9_MAIN_CROSSBOW', nombre: 'T9 Main Crossbow' },
  { id: 'T9_MAIN_CURSEDSTAFF', nombre: 'T9 Main Cursedstaff' },
  { id: 'T9_MAIN_DAGGER', nombre: 'T9 Main Dagger' },
  { id: 'T9_MAIN_FIRESTAFF', nombre: 'T9 Main Firestaff' },
  { id: 'T9_MAIN_HOLYSTAFF', nombre: 'T9 Main Holystaff' },
  { id: 'T9_MAIN_MACE', nombre: 'T9 Main Mace' },
  { id: 'T9_MAIN_NATURESTAFF', nombre: 'T9 Main Naturestaff' },
  { id: 'T9_MAIN_SPEAR', nombre: 'T9 Main Spear' },
  { id: 'T9_MAIN_SWORD', nombre: 'T9 Main Sword' },
  { id: 'T9_OFF_BOOK', nombre: 'T9 Off Book' },
  { id: 'T9_OFF_HORN', nombre: 'T9 Off Horn' },
  { id: 'T9_OFF_ORB', nombre: 'T9 Off Orb' },
  { id: 'T9_OFF_SHIELD', nombre: 'T9 Off Shield' },
  { id: 'T9_OFF_SPIKEDSHIELD', nombre: 'T9 Off Spikedshield' },
  { id: 'T9_OFF_TOWERSHIELD', nombre: 'T9 Off Towershield' },
  { id: 'T9_SHOES_CLOTH_SET1', nombre: 'T9 Shoes Cloth Set1' },
  { id: 'T9_SHOES_LEATHER_SET1', nombre: 'T9 Shoes Leather Set1' },
  { id: 'T9_SHOES_PLATE_SET1', nombre: 'T9 Shoes Plate Set1' },
  { id: 'T4_JOURNAL_FIBER', nombre: 'T4 Journal Fiber' },
  { id: 'T5_JOURNAL_FIBER', nombre: 'T5 Journal Fiber' },
  { id: 'T6_JOURNAL_FIBER', nombre: 'T6 Journal Fiber' },
  { id: 'T7_JOURNAL_FIBER', nombre: 'T7 Journal Fiber' },
  { id: 'T8_JOURNAL_FIBER', nombre: 'T8 Journal Fiber' },
  { id: 'T4_JOURNAL_HIDE', nombre: 'T4 Journal Hide' },
  { id: 'T5_JOURNAL_HIDE', nombre: 'T5 Journal Hide' },
  { id: 'T6_JOURNAL_HIDE', nombre: 'T6 Journal Hide' },
  { id: 'T7_JOURNAL_HIDE', nombre: 'T7 Journal Hide' },
  { id: 'T8_JOURNAL_HIDE', nombre: 'T8 Journal Hide' },
  { id: 'T4_JOURNAL_ORE', nombre: 'T4 Journal Ore' },
  { id: 'T5_JOURNAL_ORE', nombre: 'T5 Journal Ore' },
  { id: 'T6_JOURNAL_ORE', nombre: 'T6 Journal Ore' },
  { id: 'T7_JOURNAL_ORE', nombre: 'T7 Journal Ore' },
  { id: 'T8_JOURNAL_ORE', nombre: 'T8 Journal Ore' },
  { id: 'T4_JOURNAL_ROCK', nombre: 'T4 Journal Rock' },
  { id: 'T5_JOURNAL_ROCK', nombre: 'T5 Journal Rock' },
  { id: 'T6_JOURNAL_ROCK', nombre: 'T6 Journal Rock' },
  { id: 'T7_JOURNAL_ROCK', nombre: 'T7 Journal Rock' },
  { id: 'T8_JOURNAL_ROCK', nombre: 'T8 Journal Rock' },
  { id: 'T4_JOURNAL_WOOD', nombre: 'T4 Journal Wood' },
  { id: 'T5_JOURNAL_WOOD', nombre: 'T5 Journal Wood' },
  { id: 'T6_JOURNAL_WOOD', nombre: 'T6 Journal Wood' },
  { id: 'T7_JOURNAL_WOOD', nombre: 'T7 Journal Wood' },
  { id: 'T8_JOURNAL_WOOD', nombre: 'T8 Journal Wood' },
  { id: 'T4_MEAL_GOAT', nombre: 'T4 Meal Goat' },
  { id: 'T5_MEAL_GOAT', nombre: 'T5 Meal Goat' },
  { id: 'T6_MEAL_GOAT', nombre: 'T6 Meal Goat' },
  { id: 'T7_MEAL_GOAT', nombre: 'T7 Meal Goat' },
  { id: 'T8_MEAL_GOAT', nombre: 'T8 Meal Goat' },
  { id: 'T4_MEAL_SHEEP', nombre: 'T4 Meal Sheep' },
  { id: 'T5_MEAL_SHEEP', nombre: 'T5 Meal Sheep' },
  { id: 'T6_MEAL_SHEEP', nombre: 'T6 Meal Sheep' },
  { id: 'T7_MEAL_SHEEP', nombre: 'T7 Meal Sheep' },
  { id: 'T8_MEAL_SHEEP', nombre: 'T8 Meal Sheep' },
  { id: 'T4_MEAL_CHICKEN', nombre: 'T4 Meal Chicken' },
  { id: 'T5_MEAL_CHICKEN', nombre: 'T5 Meal Chicken' },
  { id: 'T6_MEAL_CHICKEN', nombre: 'T6 Meal Chicken' },
  { id: 'T7_MEAL_CHICKEN', nombre: 'T7 Meal Chicken' },
  { id: 'T8_MEAL_CHICKEN', nombre: 'T8 Meal Chicken' },
  { id: 'T4_MEAL_PORK', nombre: 'T4 Meal Pork' },
  { id: 'T5_MEAL_PORK', nombre: 'T5 Meal Pork' },
  { id: 'T6_MEAL_PORK', nombre: 'T6 Meal Pork' },
  { id: 'T7_MEAL_PORK', nombre: 'T7 Meal Pork' },
  { id: 'T8_MEAL_PORK', nombre: 'T8 Meal Pork' },
  { id: 'T4_MEAL_COW', nombre: 'T4 Meal Cow' },
  { id: 'T5_MEAL_COW', nombre: 'T5 Meal Cow' },
  { id: 'T6_MEAL_COW', nombre: 'T6 Meal Cow' },
  { id: 'T7_MEAL_COW', nombre: 'T7 Meal Cow' },
  { id: 'T8_MEAL_COW', nombre: 'T8 Meal Cow' },
  { id: 'T4_MEAL_GOOSE', nombre: 'T4 Meal Goose' },
  { id: 'T5_MEAL_GOOSE', nombre: 'T5 Meal Goose' },
  { id: 'T6_MEAL_GOOSE', nombre: 'T6 Meal Goose' },
  { id: 'T7_MEAL_GOOSE', nombre: 'T7 Meal Goose' },
  { id: 'T8_MEAL_GOOSE', nombre: 'T8 Meal Goose' },
  { id: 'T4_MEAL_TURKEY', nombre: 'T4 Meal Turkey' },
  { id: 'T5_MEAL_TURKEY', nombre: 'T5 Meal Turkey' },
  { id: 'T6_MEAL_TURKEY', nombre: 'T6 Meal Turkey' },
  { id: 'T7_MEAL_TURKEY', nombre: 'T7 Meal Turkey' },
  { id: 'T8_MEAL_TURKEY', nombre: 'T8 Meal Turkey' },
  { id: 'T4_MEAL_DUCK', nombre: 'T4 Meal Duck' },
  { id: 'T5_MEAL_DUCK', nombre: 'T5 Meal Duck' },
  { id: 'T6_MEAL_DUCK', nombre: 'T6 Meal Duck' },
  { id: 'T7_MEAL_DUCK', nombre: 'T7 Meal Duck' },
  { id: 'T8_MEAL_DUCK', nombre: 'T8 Meal Duck' },
  { id: 'T4_MEAL_OX', nombre: 'T4 Meal Ox' },
  { id: 'T5_MEAL_OX', nombre: 'T5 Meal Ox' },
  { id: 'T6_MEAL_OX', nombre: 'T6 Meal Ox' },
  { id: 'T7_MEAL_OX', nombre: 'T7 Meal Ox' },
  { id: 'T8_MEAL_OX', nombre: 'T8 Meal Ox' },
  { id: 'T4_MEAL_HORSE', nombre: 'T4 Meal Horse' },
  { id: 'T5_MEAL_HORSE', nombre: 'T5 Meal Horse' },
  { id: 'T6_MEAL_HORSE', nombre: 'T6 Meal Horse' },
  { id: 'T7_MEAL_HORSE', nombre: 'T7 Meal Horse' },
  { id: 'T8_MEAL_HORSE', nombre: 'T8 Meal Horse' },
  { id: 'T4_MEAL_MAMMOTH', nombre: 'T4 Meal Mammoth' },
  { id: 'T5_MEAL_MAMMOTH', nombre: 'T5 Meal Mammoth' },
  { id: 'T6_MEAL_MAMMOTH', nombre: 'T6 Meal Mammoth' },
  { id: 'T7_MEAL_MAMMOTH', nombre: 'T7 Meal Mammoth' },
  { id: 'T8_MEAL_MAMMOTH', nombre: 'T8 Meal Mammoth' },
  { id: 'T4_MEAL_SPECTER', nombre: 'T4 Meal Specter' },
  { id: 'T5_MEAL_SPECTER', nombre: 'T5 Meal Specter' },
  { id: 'T6_MEAL_SPECTER', nombre: 'T6 Meal Specter' },
  { id: 'T7_MEAL_SPECTER', nombre: 'T7 Meal Specter' },
  { id: 'T8_MEAL_SPECTER', nombre: 'T8 Meal Specter' },
  { id: 'T4_MEAL_TERRORBIRD', nombre: 'T4 Meal Terrorbird' },
  { id: 'T5_MEAL_TERRORBIRD', nombre: 'T5 Meal Terrorbird' },
  { id: 'T6_MEAL_TERRORBIRD', nombre: 'T6 Meal Terrorbird' },
  { id: 'T7_MEAL_TERRORBIRD', nombre: 'T7 Meal Terrorbird' },
  { id: 'T8_MEAL_TERRORBIRD', nombre: 'T8 Meal Terrorbird' },
  { id: 'T4_MEAL_BEAR', nombre: 'T4 Meal Bear' },
  { id: 'T5_MEAL_BEAR', nombre: 'T5 Meal Bear' },
  { id: 'T6_MEAL_BEAR', nombre: 'T6 Meal Bear' },
  { id: 'T7_MEAL_BEAR', nombre: 'T7 Meal Bear' },
  { id: 'T8_MEAL_BEAR', nombre: 'T8 Meal Bear' },
  { id: 'T4_MEAL_SWAMPDRAGON', nombre: 'T4 Meal Swamp Dragon' },
  { id: 'T5_MEAL_SWAMPDRAGON', nombre: 'T5 Meal Swamp Dragon' },
  { id: 'T6_MEAL_SWAMPDRAGON', nombre: 'T6 Meal Swamp Dragon' },
  { id: 'T7_MEAL_SWAMPDRAGON', nombre: 'T7 Meal Swamp Dragon' },
  { id: 'T8_MEAL_SWAMPDRAGON', nombre: 'T8 Meal Swamp Dragon' },
  { id: 'T4_MEAL_UNDEADBOAR', nombre: 'T4 Meal Undead Boar' },
  { id: 'T5_MEAL_UNDEADBOAR', nombre: 'T5 Meal Undead Boar' },
  { id: 'T6_MEAL_UNDEADBOAR', nombre: 'T6 Meal Undead Boar' },
  { id: 'T7_MEAL_UNDEADBOAR', nombre: 'T7 Meal Undead Boar' },
  { id: 'T8_MEAL_UNDEADBOAR', nombre: 'T8 Meal Undead Boar' },
  { id: 'T4_MEAL_MOOSE', nombre: 'T4 Meal Moose' },
  { id: 'T5_MEAL_MOOSE', nombre: 'T5 Meal Moose' },
  { id: 'T6_MEAL_MOOSE', nombre: 'T6 Meal Moose' },
  { id: 'T7_MEAL_MOOSE', nombre: 'T7 Meal Moose' },
  { id: 'T8_MEAL_MOOSE', nombre: 'T8 Meal Moose' },
  { id: 'T4_MEAL_GIANTSTAG', nombre: 'T4 Meal Giant Stag' },
  { id: 'T5_MEAL_GIANTSTAG', nombre: 'T5 Meal Giant Stag' },
  { id: 'T6_MEAL_GIANTSTAG', nombre: 'T6 Meal Giant Stag' },
  { id: 'T7_MEAL_GIANTSTAG', nombre: 'T7 Meal Giant Stag' },
  { id: 'T8_MEAL_GIANTSTAG', nombre: 'T8 Meal Giant Stag' },
  { id: 'T4_MEAL_HELLBOAR', nombre: 'T4 Meal Hellboar' },
  { id: 'T5_MEAL_HELLBOAR', nombre: 'T5 Meal Hellboar' },
  { id: 'T6_MEAL_HELLBOAR', nombre: 'T6 Meal Hellboar' },
  { id: 'T7_MEAL_HELLBOAR', nombre: 'T7 Meal Hellboar' },
  { id: 'T8_MEAL_HELLBOAR', nombre: 'T8 Meal Hellboar' },
  { id: 'T4_MEAL_FROSTRAM', nombre: 'T4 Meal Frost Ram' },
  { id: 'T5_MEAL_FROSTRAM', nombre: 'T5 Meal Frost Ram' },
  { id: 'T6_MEAL_FROSTRAM', nombre: 'T6 Meal Frost Ram' },
  { id: 'T7_MEAL_FROSTRAM', nombre: 'T7 Meal Frost Ram' },
  { id: 'T8_MEAL_FROSTRAM', nombre: 'T8 Meal Frost Ram' },
  { id: 'T4_MEAL_GHOSTWOLF', nombre: 'T4 Meal Ghost Wolf' },
  { id: 'T5_MEAL_GHOSTWOLF', nombre: 'T5 Meal Ghost Wolf' },
  { id: 'T6_MEAL_GHOSTWOLF', nombre: 'T6 Meal Ghost Wolf' },
  { id: 'T7_MEAL_GHOSTWOLF', nombre: 'T7 Meal Ghost Wolf' },
  { id: 'T8_MEAL_GHOSTWOLF', nombre: 'T8 Meal Ghost Wolf' },
  { id: 'T4_MEAL_BASILISK', nombre: 'T4 Meal Basilisk' },
  { id: 'T5_MEAL_BASILISK', nombre: 'T5 Meal Basilisk' },
  { id: 'T6_MEAL_BASILISK', nombre: 'T6 Meal Basilisk' },
  { id: 'T7_MEAL_BASILISK', nombre: 'T7 Meal Basilisk' },
  { id: 'T8_MEAL_BASILISK', nombre: 'T8 Meal Basilisk' },
  { id: 'T4_MEAL_HORNET', nombre: 'T4 Meal Hornet' },
  { id: 'T5_MEAL_HORNET', nombre: 'T5 Meal Hornet' },
  { id: 'T6_MEAL_HORNET', nombre: 'T6 Meal Hornet' },
  { id: 'T7_MEAL_HORNET', nombre: 'T7 Meal Hornet' },
  { id: 'T8_MEAL_HORNET', nombre: 'T8 Meal Hornet' },
  { id: 'T4_MEAL_DIREBEAR', nombre: 'T4 Meal Direbear' },
  { id: 'T5_MEAL_DIREBEAR', nombre: 'T5 Meal Direbear' },
  { id: 'T6_MEAL_DIREBEAR', nombre: 'T6 Meal Direbear' },
  { id: 'T7_MEAL_DIREBEAR', nombre: 'T7 Meal Direbear' },
  { id: 'T8_MEAL_DIREBEAR', nombre: 'T8 Meal Direbear' },
  { id: 'T4_MEAL_DIREWOLF', nombre: 'T4 Meal Direwolf' },
  { id: 'T5_MEAL_DIREWOLF', nombre: 'T5 Meal Direwolf' },
  { id: 'T6_MEAL_DIREWOLF', nombre: 'T6 Meal Direwolf' },
  { id: 'T7_MEAL_DIREWOLF', nombre: 'T7 Meal Direwolf' },
  { id: 'T8_MEAL_DIREWOLF', nombre: 'T8 Meal Direwolf' },
  { id: 'T4_MEAL_GIANTWOLF', nombre: 'T4 Meal Giant Wolf' },
  { id: 'T5_MEAL_GIANTWOLF', nombre: 'T5 Meal Giant Wolf' },
  { id: 'T6_MEAL_GIANTWOLF', nombre: 'T6 Meal Giant Wolf' },
  { id: 'T7_MEAL_GIANTWOLF', nombre: 'T7 Meal Giant Wolf' },
  { id: 'T8_MEAL_GIANTWOLF', nombre: 'T8 Meal Giant Wolf' },
  { id: 'T4_MEAL_TERRORBIRD', nombre: 'T4 Meal Terrorbird' },
  { id: 'T5_MEAL_TERRORBIRD', nombre: 'T5 Meal Terrorbird' },
  { id: 'T6_MEAL_TERRORBIRD', nombre: 'T6 Meal Terrorbird' },
  { id: 'T7_MEAL_TERRORBIRD', nombre: 'T7 Meal Terrorbird' },
  { id: 'T8_MEAL_TERRORBIRD', nombre: 'T8 Meal Terrorbird' },
  { id: 'T4_MEAL_SWAMPDRAGON', nombre: 'T4 Meal Swamp Dragon' },
  { id: 'T5_MEAL_SWAMPDRAGON', nombre: 'T5 Meal Swamp Dragon' },
  { id: 'T6_MEAL_SWAMPDRAGON', nombre: 'T6 Meal Swamp Dragon' },
  { id: 'T7_MEAL_SWAMPDRAGON', nombre: 'T7 Meal Swamp Dragon' },
  { id: 'T8_MEAL_SWAMPDRAGON', nombre: 'T8 Meal Swamp Dragon' },
  { id: 'T4_MEAL_SABERTOOTH', nombre: 'T4 Meal Sabertooth' },
  { id: 'T5_MEAL_SABERTOOTH', nombre: 'T5 Meal Sabertooth' },
  { id: 'T6_MEAL_SABERTOOTH', nombre: 'T6 Meal Sabertooth' },
  { id: 'T7_MEAL_SABERTOOTH', nombre: 'T7 Meal Sabertooth' },
  { id: 'T8_MEAL_SABERTOOTH', nombre: 'T8 Meal Sabertooth' },
  { id: 'T4_MEAL_FIRELIZARD', nombre: 'T4 Meal Fire Lizard' },
  { id: 'T5_MEAL_FIRELIZARD', nombre: 'T5 Meal Fire Lizard' },
  { id: 'T6_MEAL_FIRELIZARD', nombre: 'T6 Meal Fire Lizard' },
  { id: 'T7_MEAL_FIRELIZARD', nombre: 'T7 Meal Fire Lizard' },
  { id: 'T8_MEAL_FIRELIZARD', nombre: 'T8 Meal Fire Lizard' },
  { id: 'T4_MEAL_ARMOREDHORSE', nombre: 'T4 Meal Armored Horse' },
  { id: 'T5_MEAL_ARMOREDHORSE', nombre: 'T5 Meal Armored Horse' },
  { id: 'T6_MEAL_ARMOREDHORSE', nombre: 'T6 Meal Armored Horse' },
  { id: 'T7_MEAL_ARMOREDHORSE', nombre: 'T7 Meal Armored Horse' },
  { id: 'T8_MEAL_ARMOREDHORSE', nombre: 'T8 Meal Armored Horse' },
  { id: 'T4_MEAL_WARHORSE', nombre: 'T4 Meal Warhorse' },
  { id: 'T5_MEAL_WARHORSE', nombre: 'T5 Meal Warhorse' },
  { id: 'T6_MEAL_WARHORSE', nombre: 'T6 Meal Warhorse' },
  { id: 'T7_MEAL_WARHORSE', nombre: 'T7 Meal Warhorse' },
  { id: 'T8_MEAL_WARHORSE', nombre: 'T8 Meal Warhorse' },
  { id: 'T4_MEAL_ELK', nombre: 'T4 Meal Elk' },
  { id: 'T5_MEAL_ELK', nombre: 'T5 Meal Elk' },
  { id: 'T6_MEAL_ELK', nombre: 'T6 Meal Elk' },
  { id: 'T7_MEAL_ELK', nombre: 'T7 Meal Elk' },
  { id: 'T8_MEAL_ELK', nombre: 'T8 Meal Elk' },
  { id: 'T4_MEAL_OX', nombre: 'T4 Meal Ox' },
  { id: 'T5_MEAL_OX', nombre: 'T5 Meal Ox' },
  { id: 'T6_MEAL_OX', nombre: 'T6 Meal Ox' },
  { id: 'T7_MEAL_OX', nombre: 'T7 Meal Ox' },
  { id: 'T8_MEAL_OX', nombre: 'T8 Meal Ox' },
  { id: 'T4_MEAL_MAMMOTH', nombre: 'T4 Meal Mammoth' },
  { id: 'T5_MEAL_MAMMOTH', nombre: 'T5 Meal Mammoth' },
  { id: 'T6_MEAL_MAMMOTH', nombre: 'T6 Meal Mammoth' },
  { id: 'T7_MEAL_MAMMOTH', nombre: 'T7 Meal Mammoth' },
  { id: 'T8_MEAL_MAMMOTH', nombre: 'T8 Meal Mammoth' },
  { id: 'T4_MEAL_SPECTRALBONEHORSE', nombre: 'T4 Meal Spectral Bonehorse' },
  { id: 'T5_MEAL_SPECTRALBONEHORSE', nombre: 'T5 Meal Spectral Bonehorse' },
  { id: 'T6_MEAL_SPECTRALBONEHORSE', nombre: 'T6 Meal Spectral Bonehorse' },
  { id: 'T7_MEAL_SPECTRALBONEHORSE', nombre: 'T7 Meal Spectral Bonehorse' },
  { id: 'T8_MEAL_SPECTRALBONEHORSE', nombre: 'T8 Meal Spectral Bonehorse' },
  { id: 'T4_MEAL_GIANTSTAG', nombre: 'T4 Meal Giant Stag' },
  { id: 'T5_MEAL_GIANTSTAG', nombre: 'T5 Meal Giant Stag' },
  { id: 'T6_MEAL_GIANTSTAG', nombre: 'T6 Meal Giant Stag' },
  { id: 'T7_MEAL_GIANTSTAG', nombre: 'T7 Meal Giant Stag' },
  { id: 'T8_MEAL_GIANTSTAG', nombre: 'T8 Meal Giant Stag' },
  { id: 'T4_MEAL_TERRORBIRDMOUNT', nombre: 'T4 Meal Terrorbird Mount' },
  { id: 'T5_MEAL_TERRORBIRDMOUNT', nombre: 'T5 Meal Terrorbird Mount' },
  { id: 'T6_MEAL_TERRORBIRDMOUNT', nombre: 'T6 Meal Terrorbird Mount' },
  { id: 'T7_MEAL_TERRORBIRDMOUNT', nombre: 'T7 Meal Terrorbird Mount' },
  { id: 'T8_MEAL_TERRORBIRDMOUNT', nombre: 'T8 Meal Terrorbird Mount' },
  { id: 'T4_MEAL_SWAMPDRAGONMOUNT', nombre: 'T4 Meal Swamp Dragon Mount' },
  { id: 'T5_MEAL_SWAMPDRAGONMOUNT', nombre: 'T5 Meal Swamp Dragon Mount' },
  { id: 'T6_MEAL_SWAMPDRAGONMOUNT', nombre: 'T6 Meal Swamp Dragon Mount' },
  { id: 'T7_MEAL_SWAMPDRAGONMOUNT', nombre: 'T7 Meal Swamp Dragon Mount' },
  { id: 'T8_MEAL_SWAMPDRAGONMOUNT', nombre: 'T8 Meal Swamp Dragon Mount' },
  { id: 'T4_MEAL_SABERTOOTHMOUNT', nombre: 'T4 Meal Sabertooth Mount' },
  { id: 'T5_MEAL_SABERTOOTHMOUNT', nombre: 'T5 Meal Sabertooth Mount' },
  { id: 'T6_MEAL_SABERTOOTHMOUNT', nombre: 'T6 Meal Sabertooth Mount' },
  { id: 'T7_MEAL_SABERTOOTHMOUNT', nombre: 'T7 Meal Sabertooth Mount' },
  { id: 'T8_MEAL_SABERTOOTHMOUNT', nombre: 'T8 Meal Sabertooth Mount' },
  { id: 'T4_MEAL_FIRELIZARDMOUNT', nombre: 'T4 Meal Fire Lizard Mount' },
  { id: 'T5_MEAL_FIRELIZARDMOUNT', nombre: 'T5 Meal Fire Lizard Mount' },
  { id: 'T6_MEAL_FIRELIZARDMOUNT', nombre: 'T6 Meal Fire Lizard Mount' },
  { id: 'T7_MEAL_FIRELIZARDMOUNT', nombre: 'T7 Meal Fire Lizard Mount' },
  { id: 'T8_MEAL_FIRELIZARDMOUNT', nombre: 'T8 Meal Fire Lizard Mount' },
  { id: 'T4_MEAL_ARMOREDHORSEMOUNT', nombre: 'T4 Meal Armored Horse Mount' },
  { id: 'T5_MEAL_ARMOREDHORSEMOUNT', nombre: 'T5 Meal Armored Horse Mount' },
  { id: 'T6_MEAL_ARMOREDHORSEMOUNT', nombre: 'T6 Meal Armored Horse Mount' },
  { id: 'T7_MEAL_ARMOREDHORSEMOUNT', nombre: 'T7 Meal Armored Horse Mount' },
  { id: 'T8_MEAL_ARMOREDHORSEMOUNT', nombre: 'T8 Meal Armored Horse Mount' },
  { id: 'T4_MEAL_WARHORSEMOUNT', nombre: 'T4 Meal Warhorse Mount' },
  { id: 'T5_MEAL_WARHORSEMOUNT', nombre: 'T5 Meal Warhorse Mount' },
  { id: 'T6_MEAL_WARHORSEMOUNT', nombre: 'T6 Meal Warhorse Mount' },
  { id: 'T7_MEAL_WARHORSEMOUNT', nombre: 'T7 Meal Warhorse Mount' },
  { id: 'T8_MEAL_WARHORSEMOUNT', nombre: 'T8 Meal Warhorse Mount' },
  { id: 'T4_MEAL_MULE', nombre: 'T4 Meal Mule' },
  { id: 'T5_MEAL_MULE', nombre: 'T5 Meal Mule' },
  { id: 'T6_MEAL_MULE', nombre: 'T6 Meal Mule' },
  { id: 'T7_MEAL_MULE', nombre: 'T7 Meal Mule' },
  { id: 'T8_MEAL_MULE', nombre: 'T8 Meal Mule' },
  { id: 'T4_MEAL_OX', nombre: 'T4 Meal Ox' },
  { id: 'T5_MEAL_OX', nombre: 'T5 Meal Ox' },
  { id: 'T6_MEAL_OX', nombre: 'T6 Meal Ox' },
  { id: 'T7_MEAL_OX', nombre: 'T7 Meal Ox' },
  { id: 'T8_MEAL_OX', nombre: 'T8 Meal Ox' },
  { id: 'T4_MEAL_GIANTOX', nombre: 'T4 Meal Giant Ox' },
  { id: 'T5_MEAL_GIANTOX', nombre: 'T5 Meal Giant Ox' },
  { id: 'T6_MEAL_GIANTOX', nombre: 'T6 Meal Giant Ox' },
  { id: 'T7_MEAL_GIANTOX', nombre: 'T7 Meal Giant Ox' },
  { id: 'T8_MEAL_GIANTOX', nombre: 'T8 Meal Giant Ox' },
  { id: 'T4_MEAL_TRANSPORTOX', nombre: 'T4 Meal Transport Ox' },
  { id: 'T5_MEAL_TRANSPORTOX', nombre: 'T5 Meal Transport Ox' },
  { id: 'T6_MEAL_TRANSPORTOX', nombre: 'T6 Meal Transport Ox' },
  { id: 'T7_MEAL_TRANSPORTOX', nombre: 'T7 Meal Transport Ox' },
  { id: 'T8_MEAL_TRANSPORTOX', nombre: 'T8 Meal Transport Ox' },
  { id: 'T4_MEAL_ARMOREDOX', nombre: 'T4 Meal Armored Ox' },
  { id: 'T5_MEAL_ARMOREDOX', nombre: 'T5 Meal Armored Ox' },
  { id: 'T6_MEAL_ARMOREDOX', nombre: 'T6 Meal Armored Ox' },
  { id: 'T7_MEAL_ARMOREDOX', nombre: 'T7 Meal Armored Ox' },
  { id: 'T8_MEAL_ARMOREDOX', nombre: 'T8 Meal Armored Ox' },
  { id: 'T4_MEAL_SPECTRALBONEOX', nombre: 'T4 Meal Spectral Bone Ox' },
  { id: 'T5_MEAL_SPECTRALBONEOX', nombre: 'T5 Meal Spectral Bone Ox' },
  { id: 'T6_MEAL_SPECTRALBONEOX', nombre: 'T6 Meal Spectral Bone Ox' },
  { id: 'T7_MEAL_SPECTRALBONEOX', nombre: 'T7 Meal Spectral Bone Ox' },
  { id: 'T8_MEAL_SPECTRALBONEOX', nombre: 'T8 Meal Spectral Bone Ox' },
  { id: 'T4_MEAL_BOAR', nombre: 'T4 Meal Boar' },
  { id: 'T5_MEAL_BOAR', nombre: 'T5 Meal Boar' },
  { id: 'T6_MEAL_BOAR', nombre: 'T6 Meal Boar' },
  { id: 'T7_MEAL_BOAR', nombre: 'T7 Meal Boar' },
  { id: 'T8_MEAL_BOAR', nombre: 'T8 Meal Boar' },
  { id: 'T4_MEAL_HORSE', nombre: 'T4 Meal Horse' },
  { id: 'T5_MEAL_HORSE', nombre: 'T5 Meal Horse' },
  { id: 'T6_MEAL_HORSE', nombre: 'T6 Meal Horse' },
  { id: 'T7_MEAL_HORSE', nombre: 'T7 Meal Horse' },
  { id: 'T8_MEAL_HORSE', nombre: 'T8 Meal Horse' },
  { id: 'T4_MEAL_COUGAR', nombre: 'T4 Meal Cougar' },
  { id: 'T5_MEAL_COUGAR', nombre: 'T5 Meal Cougar' },
  { id: 'T6_MEAL_COUGAR', nombre: 'T6 Meal Cougar' },
  { id: 'T7_MEAL_COUGAR', nombre: 'T7 Meal Cougar' },
  { id: 'T8_MEAL_COUGAR', nombre: 'T8 Meal Cougar' },
  { id: 'T4_MEAL_MONSTER', nombre: 'T4 Meal Monster' },
  { id: 'T5_MEAL_MONSTER', nombre: 'T5 Meal Monster' },
  { id: 'T6_MEAL_MONSTER', nombre: 'T6 Meal Monster' },
  { id: 'T7_MEAL_MONSTER', nombre: 'T7 Meal Monster' },
  { id: 'T8_MEAL_MONSTER', nombre: 'T8 Meal Monster' },
  { id: 'T4_MEAL_HUNTER', nombre: 'T4 Meal Hunter' },
  { id: 'T5_MEAL_HUNTER', nombre: 'T5 Meal Hunter' },
  { id: 'T6_MEAL_HUNTER', nombre: 'T6 Meal Hunter' },
  { id: 'T7_MEAL_HUNTER', nombre: 'T7 Meal Hunter' },
  { id: 'T8_MEAL_HUNTER', nombre: 'T8 Meal Hunter' },
  { id: 'T4_MEAL_GATHERER', nombre: 'T4 Meal Gatherer' },
  { id: 'T5_MEAL_GATHERER', nombre: 'T5 Meal Gatherer' },
  { id: 'T6_MEAL_GATHERER', nombre: 'T6 Meal Gatherer' },
  { id: 'T7_MEAL_GATHERER', nombre: 'T7 Meal Gatherer' },
  { id: 'T8_MEAL_GATHERER', nombre: 'T8 Meal Gatherer' },
  { id: 'T4_MEAL_GATHERER_SANDSTONE', nombre: 'T4 Meal Gatherer Sandstone' },
  { id: 'T5_MEAL_GATHERER_SANDSTONE', nombre: 'T5 Meal Gatherer Sandstone' },
  { id: 'T6_MEAL_GATHERER_SANDSTONE', nombre: 'T6 Meal Gatherer Sandstone' },
  { id: 'T7_MEAL_GATHERER_SANDSTONE', nombre: 'T7 Meal Gatherer Sandstone' },
  { id: 'T8_MEAL_GATHERER_SANDSTONE', nombre: 'T8 Meal Gatherer Sandstone' },
  { id: 'T4_MEAL_GATHERER_FIBER', nombre: 'T4 Meal Gatherer Fiber' },
  { id: 'T5_MEAL_GATHERER_FIBER', nombre: 'T5 Meal Gatherer Fiber' },
  { id: 'T6_MEAL_GATHERER_FIBER', nombre: 'T6 Meal Gatherer Fiber' },
  { id: 'T7_MEAL_GATHERER_FIBER', nombre: 'T7 Meal Gatherer Fiber' },
  { id: 'T8_MEAL_GATHERER_FIBER', nombre: 'T8 Meal Gatherer Fiber' },
  { id: 'T4_MEAL_GATHERER_HIDE', nombre: 'T4 Meal Gatherer Hide' },
  { id: 'T5_MEAL_GATHERER_HIDE', nombre: 'T5 Meal Gatherer Hide' },
  { id: 'T6_MEAL_GATHERER_HIDE', nombre: 'T6 Meal Gatherer Hide' },
  { id: 'T7_MEAL_GATHERER_HIDE', nombre: 'T7 Meal Gatherer Hide' },
  { id: 'T8_MEAL_GATHERER_HIDE', nombre: 'T8 Meal Gatherer Hide' },
  { id: 'T4_MEAL_GATHERER_ORE', nombre: 'T4 Meal Gatherer Ore' },
  { id: 'T5_MEAL_GATHERER_ORE', nombre: 'T5 Meal Gatherer Ore' },
  { id: 'T6_MEAL_GATHERER_ORE', nombre: 'T6 Meal Gatherer Ore' },
  { id: 'T7_MEAL_GATHERER_ORE', nombre: 'T7 Meal Gatherer Ore' },
  { id: 'T8_MEAL_GATHERER_ORE', nombre: 'T8 Meal Gatherer Ore' },
  { id: 'T4_MEAL_GATHERER_WOOD', nombre: 'T4 Meal Gatherer Wood' },
  { id: 'T5_MEAL_GATHERER_WOOD', nombre: 'T5 Meal Gatherer Wood' },
  { id: 'T6_MEAL_GATHERER_WOOD', nombre: 'T6 Meal Gatherer Wood' },
  { id: 'T7_MEAL_GATHERER_WOOD', nombre: 'T7 Meal Gatherer Wood' },
  { id: 'T8_MEAL_GATHERER_WOOD', nombre: 'T8 Meal Gatherer Wood' },
  { id: 'T4_MEAL_GATHERER_ALL', nombre: 'T4 Meal Gatherer All' },
  { id: 'T5_MEAL_GATHERER_ALL', nombre: 'T5 Meal Gatherer All' },
  { id: 'T6_MEAL_GATHERER_ALL', nombre: 'T6 Meal Gatherer All' },
  { id: 'T7_MEAL_GATHERER_ALL', nombre: 'T7 Meal Gatherer All' },
  { id: 'T8_MEAL_GATHERER_ALL', nombre: 'T8 Meal Gatherer All' },
  { id: 'T4_MEAL_COOKED', nombre: 'T4 Meal Cooked' },
  { id: 'T5_MEAL_COOKED', nombre: 'T5 Meal Cooked' },
  { id: 'T6_MEAL_COOKED', nombre: 'T6 Meal Cooked' },
  { id: 'T7_MEAL_COOKED', nombre: 'T7 Meal Cooked' },
  { id: 'T8_MEAL_COOKED', nombre: 'T8 Meal Cooked' },
  { id: 'T4_MEAL_SALAD', nombre: 'T4 Meal Salad' },
  { id: 'T5_MEAL_SALAD', nombre: 'T5 Meal Salad' },
  { id: 'T6_MEAL_SALAD', nombre: 'T6 Meal Salad' },
  { id: 'T7_MEAL_SALAD', nombre: 'T7 Meal Salad' },
  { id: 'T8_MEAL_SALAD', nombre: 'T8 Meal Salad' },
  { id: 'T4_MEAL_SOUP', nombre: 'T4 Meal Soup' },
  { id: 'T5_MEAL_SOUP', nombre: 'T5 Meal Soup' },
  { id: 'T6_MEAL_SOUP', nombre: 'T6 Meal Soup' },
  { id: 'T7_MEAL_SOUP', nombre: 'T7 Meal Soup' },
  { id: 'T8_MEAL_SOUP', nombre: 'T8 Meal Soup' },
  { id: 'T4_MEAL_OMELETTE', nombre: 'T4 Meal Omelette' },
  { id: 'T5_MEAL_OMELETTE', nombre: 'T5 Meal Omelette' },
  { id: 'T6_MEAL_OMELETTE', nombre: 'T6 Meal Omelette' },
  { id: 'T7_MEAL_OMELETTE', nombre: 'T7 Meal Omelette' },
  { id: 'T8_MEAL_OMELETTE', nombre: 'T8 Meal Omelette' },
  { id: 'T4_MEAL_ROAST', nombre: 'T4 Meal Roast' },
  { id: 'T5_MEAL_ROAST', nombre: 'T5 Meal Roast' },
  { id: 'T6_MEAL_ROAST', nombre: 'T6 Meal Roast' },
  { id: 'T7_MEAL_ROAST', nombre: 'T7 Meal Roast' },
  { id: 'T8_MEAL_ROAST', nombre: 'T8 Meal Roast' },
  { id: 'T4_MEAL_PIE', nombre: 'T4 Meal Pie' },
  { id: 'T5_MEAL_PIE', nombre: 'T5 Meal Pie' },
  { id: 'T6_MEAL_PIE', nombre: 'T6 Meal Pie' },
  { id: 'T7_MEAL_PIE', nombre: 'T7 Meal Pie' },
  { id: 'T8_MEAL_PIE', nombre: 'T8 Meal Pie' },
  { id: 'T4_MEAL_PUDDING', nombre: 'T4 Meal Pudding' },
  { id: 'T5_MEAL_PUDDING', nombre: 'T5 Meal Pudding' },
  { id: 'T6_MEAL_PUDDING', nombre: 'T6 Meal Pudding' },
  { id: 'T7_MEAL_PUDDING', nombre: 'T7 Meal Pudding' },
  { id: 'T8_MEAL_PUDDING', nombre: 'T8 Meal Pudding' },
  { id: 'T4_MEAL_SANDWICH', nombre: 'T4 Meal Sandwich' },
  { id: 'T5_MEAL_SANDWICH', nombre: 'T5 Meal Sandwich' },
  { id: 'T6_MEAL_SANDWICH', nombre: 'T6 Meal Sandwich' },
  { id: 'T7_MEAL_SANDWICH', nombre: 'T7 Meal Sandwich' },
  { id: 'T8_MEAL_SANDWICH', nombre: 'T8 Meal Sandwich' },
  { id: 'T4_MEAL_STEW', nombre: 'T4 Meal Stew' },
  { id: 'T5_MEAL_STEW', nombre: 'T5 Meal Stew' },
  { id: 'T6_MEAL_STEW', nombre: 'T6 Meal Stew' },
  { id: 'T7_MEAL_STEW', nombre: 'T7 Meal Stew' },
  { id: 'T8_MEAL_STEW', nombre: 'T8 Meal Stew' },
  { id: 'T4_MEAL_PASTA', nombre: 'T4 Meal Pasta' },
  { id: 'T5_MEAL_PASTA', nombre: 'T5 Meal Pasta' },
  { id: 'T6_MEAL_PASTA', nombre: 'T6 Meal Pasta' },
  { id: 'T7_MEAL_PASTA', nombre: 'T7 Meal Pasta' },
  { id: 'T8_MEAL_PASTA', nombre: 'T8 Meal Pasta' },
  { id: 'T4_MEAL_CURRY', nombre: 'T4 Meal Curry' },
  { id: 'T5_MEAL_CURRY', nombre: 'T5 Meal Curry' },
  { id: 'T6_MEAL_CURRY', nombre: 'T6 Meal Curry' },
  { id: 'T7_MEAL_CURRY', nombre: 'T7 Meal Curry' },
  { id: 'T8_MEAL_CURRY', nombre: 'T8 Meal Curry' },
  { id: 'T4_MEAL_TACOS', nombre: 'T4 Meal Tacos' },
  { id: 'T5_MEAL_TACOS', nombre: 'T5 Meal Tacos' },
  { id: 'T6_MEAL_TACOS', nombre: 'T6 Meal Tacos' },
  { id: 'T7_MEAL_TACOS', nombre: 'T7 Meal Tacos' },
  { id: 'T8_MEAL_TACOS', nombre: 'T8 Meal Tacos' },
  { id: 'T4_MEAL_CHILI', nombre: 'T4 Meal Chili' },
  { id: 'T5_MEAL_CHILI', nombre: 'T5 Meal Chili' },
  { id: 'T6_MEAL_CHILI', nombre: 'T6 Meal Chili' },
  { id: 'T7_MEAL_CHILI', nombre: 'T7 Meal Chili' },
  { id: 'T8_MEAL_CHILI', nombre: 'T8 Meal Chili' },
  { id: 'T4_MEAL_SUSHI', nombre: 'T4 Meal Sushi' },
  { id: 'T5_MEAL_SUSHI', nombre: 'T5 Meal Sushi' },
  { id: 'T6_MEAL_SUSHI', nombre: 'T6 Meal Sushi' },
  { id: 'T7_MEAL_SUSHI', nombre: 'T7 Meal Sushi' },
  { id: 'T8_MEAL_SUSHI', nombre: 'T8 Meal Sushi' },
  { id: 'T4_MEAL_NOODLES', nombre: 'T4 Meal Noodles' },
  { id: 'T5_MEAL_NOODLES', nombre: 'T5 Meal Noodles' },
  { id: 'T6_MEAL_NOODLES', nombre: 'T6 Meal Noodles' },
  { id: 'T7_MEAL_NOODLES', nombre: 'T7 Meal Noodles' },
  { id: 'T8_MEAL_NOODLES', nombre: 'T8 Meal Noodles' },
  { id: 'T4_MEAL_BURRITO', nombre: 'T4 Meal Burrito' },
  { id: 'T5_MEAL_BURRITO', nombre: 'T5 Meal Burrito' },
  { id: 'T6_MEAL_BURRITO', nombre: 'T6 Meal Burrito' },
  { id: 'T7_MEAL_BURRITO', nombre: 'T7 Meal Burrito' },
  { id: 'T8_MEAL_BURRITO', nombre: 'T8 Meal Burrito' },
  { id: 'T4_MEAL_SAUSAGE', nombre: 'T4 Meal Sausage' },
  { id: 'T5_MEAL_SAUSAGE', nombre: 'T5 Meal Sausage' },
  { id: 'T6_MEAL_SAUSAGE', nombre: 'T6 Meal Sausage' },
  { id: 'T7_MEAL_SAUSAGE', nombre: 'T7 Meal Sausage' },
  { id: 'T8_MEAL_SAUSAGE', nombre: 'T8 Meal Sausage' },
  { id: 'T4_MEAL_PASTRY', nombre: 'T4 Meal Pastry' },
  { id: 'T5_MEAL_PASTRY', nombre: 'T5 Meal Pastry' },
  { id: 'T6_MEAL_PASTRY', nombre: 'T6 Meal Pastry' },
  { id: 'T7_MEAL_PASTRY', nombre: 'T7 Meal Pastry' },
  { id: 'T8_MEAL_PASTRY', nombre: 'T8 Meal Pastry' },
  { id: 'T4_MEAL_FRIEDVEGGIES', nombre: 'T4 Meal Fried Veggies' },
  { id: 'T5_MEAL_FRIEDVEGGIES', nombre: 'T5 Meal Fried Veggies' },
  { id: 'T6_MEAL_FRIEDVEGGIES', nombre: 'T6 Meal Fried Veggies' },
  { id: 'T7_MEAL_FRIEDVEGGIES', nombre: 'T7 Meal Fried Veggies' },
  { id: 'T8_MEAL_FRIEDVEGGIES', nombre: 'T8 Meal Fried Veggies' },
  { id: 'T4_MEAL_STIRFRY', nombre: 'T4 Meal Stir Fry' },
  { id: 'T5_MEAL_STIRFRY', nombre: 'T5 Meal Stir Fry' },
  { id: 'T6_MEAL_STIRFRY', nombre: 'T6 Meal Stir Fry' },
  { id: 'T7_MEAL_STIRFRY', nombre: 'T7 Meal Stir Fry' },
  { id: 'T8_MEAL_STIRFRY', nombre: 'T8 Meal Stir Fry' },
  { id: 'T4_MEAL_KABOBS', nombre: 'T4 Meal Kabobs' },
  { id: 'T5_MEAL_KABOBS', nombre: 'T5 Meal Kabobs' },
  { id: 'T6_MEAL_KABOBS', nombre: 'T6 Meal Kabobs' },
  { id: 'T7_MEAL_KABOBS', nombre: 'T7 Meal Kabobs' },
  { id: 'T8_MEAL_KABOBS', nombre: 'T8 Meal Kabobs' },
  { id: 'T4_MEAL_BBQ', nombre: 'T4 Meal BBQ' },
  { id: 'T5_MEAL_BBQ', nombre: 'T5 Meal BBQ' },
  { id: 'T6_MEAL_BBQ', nombre: 'T6 Meal BBQ' },
  { id: 'T7_MEAL_BBQ', nombre: 'T7 Meal BBQ' },
  { id: 'T8_MEAL_BBQ', nombre: 'T8 Meal BBQ' },
  { id: 'T4_MEAL_ROAST', nombre: 'T4 Meal Roast' },
  { id: 'T5_MEAL_ROAST', nombre: 'T5 Meal Roast' },
  { id: 'T6_MEAL_ROAST', nombre: 'T6 Meal Roast' },
  { id: 'T7_MEAL_ROAST', nombre: 'T7 Meal Roast' },
  { id: 'T8_MEAL_ROAST', nombre: 'T8 Meal Roast' },
  { id: 'T4_MEAL_PIE', nombre: 'T4 Meal Pie' },
  { id: 'T5_MEAL_PIE', nombre: 'T5 Meal Pie' },
  { id: 'T6_MEAL_PIE', nombre: 'T6 Meal Pie' },
  { id: 'T7_MEAL_PIE', nombre: 'T7 Meal Pie' },
  { id: 'T8_MEAL_PIE', nombre: 'T8 Meal Pie' },
  { id: 'T4_MEAL_CURRY', nombre: 'T4 Meal Curry' },
  { id: 'T5_MEAL_CURRY', nombre: 'T5 Meal Curry' },
  { id: 'T6_MEAL_CURRY', nombre: 'T6 Meal Curry' },
  { id: 'T7_MEAL_CURRY', nombre: 'T7 Meal Curry' },
  { id: 'T8_MEAL_CURRY', nombre: 'T8 Meal Curry' },
  { id: 'T4_MEAL_OMELETTE', nombre: 'T4 Meal Omelette' },
  { id: 'T5_MEAL_OMELETTE', nombre: 'T5 Meal Omelette' },
  { id: 'T6_MEAL_OMELETTE', nombre: 'T6 Meal Omelette' },
  { id: 'T7_MEAL_OMELETTE', nombre: 'T7 Meal Omelette' },
  { id: 'T8_MEAL_OMELETTE', nombre: 'T8 Meal Omelette' },
  { id: 'T4_MEAL_POTATOES', nombre: 'T4 Meal Potatoes' },
  { id: 'T5_MEAL_POTATOES', nombre: 'T5 Meal Potatoes' },
  { id: 'T6_MEAL_POTATOES', nombre: 'T6 Meal Potatoes' },
  { id: 'T7_MEAL_POTATOES', nombre: 'T7 Meal Potatoes' },
  { id: 'T8_MEAL_POTATOES', nombre: 'T8 Meal Potatoes' },
  { id: 'T4_MEAL_CASSEROLE', nombre: 'T4 Meal Casserole' },
  { id: 'T5_MEAL_CASSEROLE', nombre: 'T5 Meal Casserole' },
  { id: 'T6_MEAL_CASSEROLE', nombre: 'T6 Meal Casserole' },
  { id: 'T7_MEAL_CASSEROLE', nombre: 'T7 Meal Casserole' },
  { id: 'T8_MEAL_CASSEROLE', nombre: 'T8 Meal Casserole' },
  { id: 'T4_MEAL_SANDWICH', nombre: 'T4 Meal Sandwich' },
  { id: 'T5_MEAL_SANDWICH', nombre: 'T5 Meal Sandwich' },
  { id: 'T6_MEAL_SANDWICH', nombre: 'T6 Meal Sandwich' },
  { id: 'T7_MEAL_SANDWICH', nombre: 'T7 Meal Sandwich' },
  { id: 'T8_MEAL_SANDWICH', nombre: 'T8 Meal Sandwich' },
  { id: 'T4_MEAL_PASTA', nombre: 'T4 Meal Pasta' },
  { id: 'T5_MEAL_PASTA', nombre: 'T5 Meal Pasta' },
  { id: 'T6_MEAL_PASTA', nombre: 'T6 Meal Pasta' },
  { id: 'T7_MEAL_PASTA', nombre: 'T7 Meal Pasta' },
  { id: 'T8_MEAL_PASTA', nombre: 'T8 Meal Pasta' },
  { id: 'T4_MEAL_TACOPLATE', nombre: 'T4 Meal Taco Plate' },
  { id: 'T5_MEAL_TACOPLATE', nombre: 'T5 Meal Taco Plate' },
  { id: 'T6_MEAL_TACOPLATE', nombre: 'T6 Meal Taco Plate' },
  { id: 'T7_MEAL_TACOPLATE', nombre: 'T7 Meal Taco Plate' },
  { id: 'T8_MEAL_TACOPLATE', nombre: 'T8 Meal Taco Plate' },
  { id: 'T4_MEAL_CURRYPLATE', nombre: 'T4 Meal Curry Plate' },
  { id: 'T5_MEAL_CURRYPLATE', nombre: 'T5 Meal Curry Plate' },
  { id: 'T6_MEAL_CURRYPLATE', nombre: 'T6 Meal Curry Plate' },
  { id: 'T7_MEAL_CURRYPLATE', nombre: 'T7 Meal Curry Plate' },
  { id: 'T8_MEAL_CURRYPLATE', nombre: 'T8 Meal Curry Plate' },
  { id: 'T4_MEAL_SUSHIPLATE', nombre: 'T4 Meal Sushi Plate' },
  { id: 'T5_MEAL_SUSHIPLATE', nombre: 'T5 Meal Sushi Plate' },
  { id: 'T6_MEAL_SUSHIPLATE', nombre: 'T6 Meal Sushi Plate' },
  { id: 'T7_MEAL_SUSHIPLATE', nombre: 'T7 Meal Sushi Plate' },
  { id: 'T8_MEAL_SUSHIPLATE', nombre: 'T8 Meal Sushi Plate' },
  { id: 'T4_MEAL_SALADPLATE', nombre: 'T4 Meal Salad Plate' },
  { id: 'T5_MEAL_SALADPLATE', nombre: 'T5 Meal Salad Plate' },
  { id: 'T6_MEAL_SALADPLATE', nombre: 'T6 Meal Salad Plate' },
  { id: 'T7_MEAL_SALADPLATE', nombre: 'T7 Meal Salad Plate' },
  { id: 'T8_MEAL_SALADPLATE', nombre: 'T8 Meal Salad Plate' },
  { id: 'T4_MEAL_FRIEDVEG', nombre: 'T4 Meal Fried Veg' },
  { id: 'T5_MEAL_FRIEDVEG', nombre: 'T5 Meal Fried Veg' },
  { id: 'T6_MEAL_FRIEDVEG', nombre: 'T6 Meal Fried Veg' },
  { id: 'T7_MEAL_FRIEDVEG', nombre: 'T7 Meal Fried Veg' },
  { id: 'T8_MEAL_FRIEDVEG', nombre: 'T8 Meal Fried Veg' },
  { id: 'T4_MEAL_AVOCADOTOAST', nombre: 'T4 Meal Avocado Toast' },
  { id: 'T5_MEAL_AVOCADOTOAST', nombre: 'T5 Meal Avocado Toast' },
  { id: 'T6_MEAL_AVOCADOTOAST', nombre: 'T6 Meal Avocado Toast' },
  { id: 'T7_MEAL_AVOCADOTOAST', nombre: 'T7 Meal Avocado Toast' },
  { id: 'T8_MEAL_AVOCADOTOAST', nombre: 'T8 Meal Avocado Toast' },
  { id: 'T4_MEAL_ICECREAM', nombre: 'T4 Meal Ice Cream' },
  { id: 'T5_MEAL_ICECREAM', nombre: 'T5 Meal Ice Cream' },
  { id: 'T6_MEAL_ICECREAM', nombre: 'T6 Meal Ice Cream' },
  { id: 'T7_MEAL_ICECREAM', nombre: 'T7 Meal Ice Cream' },
  { id: 'T8_MEAL_ICECREAM', nombre: 'T8 Meal Ice Cream' },
  { id: 'T4_MEAL_PORRIDGE', nombre: 'T4 Meal Porridge' },
  { id: 'T5_MEAL_PORRIDGE', nombre: 'T5 Meal Porridge' },
  { id: 'T6_MEAL_PORRIDGE', nombre: 'T6 Meal Porridge' },
  { id: 'T7_MEAL_PORRIDGE', nombre: 'T7 Meal Porridge' },
  { id: 'T8_MEAL_PORRIDGE', nombre: 'T8 Meal Porridge' },
  { id: 'T4_MEAL_NOODLE', nombre: 'T4 Meal Noodle' },
  { id: 'T5_MEAL_NOODLE', nombre: 'T5 Meal Noodle' },
  { id: 'T6_MEAL_NOODLE', nombre: 'T6 Meal Noodle' },
  { id: 'T7_MEAL_NOODLE', nombre: 'T7 Meal Noodle' },
  { id: 'T8_MEAL_NOODLE', nombre: 'T8 Meal Noodle' },
  { id: 'T4_MEAL_HAMBURGER', nombre: 'T4 Meal Hamburger' },
  { id: 'T5_MEAL_HAMBURGER', nombre: 'T5 Meal Hamburger' },
  { id: 'T6_MEAL_HAMBURGER', nombre: 'T6 Meal Hamburger' },
  { id: 'T7_MEAL_HAMBURGER', nombre: 'T7 Meal Hamburger' },
  { id: 'T8_MEAL_HAMBURGER', nombre: 'T8 Meal Hamburger' },
  { id: 'T4_MEAL_PIZZA', nombre: 'T4 Meal Pizza' },
  { id: 'T5_MEAL_PIZZA', nombre: 'T5 Meal Pizza' },
  { id: 'T6_MEAL_PIZZA', nombre: 'T6 Meal Pizza' },
  { id: 'T7_MEAL_PIZZA', nombre: 'T7 Meal Pizza' },
  { id: 'T8_MEAL_PIZZA', nombre: 'T8 Meal Pizza' },
  { id: 'T4_MEAL_SANDWICHVEG', nombre: 'T4 Meal Veg Sandwich' },
  { id: 'T5_MEAL_SANDWICHVEG', nombre: 'T5 Meal Veg Sandwich' },
  { id: 'T6_MEAL_SANDWICHVEG', nombre: 'T6 Meal Veg Sandwich' },
  { id: 'T7_MEAL_SANDWICHVEG', nombre: 'T7 Meal Veg Sandwich' },
  { id: 'T8_MEAL_SANDWICHVEG', nombre: 'T8 Meal Veg Sandwich' },
  { id: 'T4_MEAL_TACOVEG', nombre: 'T4 Meal Veg Taco' },
  { id: 'T5_MEAL_TACOVEG', nombre: 'T5 Meal Veg Taco' },
  { id: 'T6_MEAL_TACOVEG', nombre: 'T6 Meal Veg Taco' },
  { id: 'T7_MEAL_TACOVEG', nombre: 'T7 Meal Veg Taco' },
  { id: 'T8_MEAL_TACOVEG', nombre: 'T8 Meal Veg Taco' },
  { id: 'T4_MEAL_STEW', nombre: 'T4 Meal Stew' },
  { id: 'T5_MEAL_STEW', nombre: 'T5 Meal Stew' },
  { id: 'T6_MEAL_STEW', nombre: 'T6 Meal Stew' },
  { id: 'T7_MEAL_STEW', nombre: 'T7 Meal Stew' },
  { id: 'T8_MEAL_STEW', nombre: 'T8 Meal Stew' },
  { id: 'T4_MEAL_STEWVEG', nombre: 'T4 Meal Veg Stew' },
  { id: 'T5_MEAL_STEWVEG', nombre: 'T5 Meal Veg Stew' },
  { id: 'T6_MEAL_STEWVEG', nombre: 'T6 Meal Veg Stew' },
  { id: 'T7_MEAL_STEWVEG', nombre: 'T7 Meal Veg Stew' },
  { id: 'T8_MEAL_STEWVEG', nombre: 'T8 Meal Veg Stew' },
  { id: 'T4_MEAL_PIE', nombre: 'T4 Meal Pie' },
  { id: 'T5_MEAL_PIE', nombre: 'T5 Meal Pie' },
  { id: 'T6_MEAL_PIE', nombre: 'T6 Meal Pie' },
  { id: 'T7_MEAL_PIE', nombre: 'T7 Meal Pie' },
  { id: 'T8_MEAL_PIE', nombre: 'T8 Meal Pie' },
  { id: 'T4_MEAL_SANDWICH', nombre: 'T4 Meal Sandwich' },
  { id: 'T5_MEAL_SANDWICH', nombre: 'T5 Meal Sandwich' },
  { id: 'T6_MEAL_SANDWICH', nombre: 'T6 Meal Sandwich' },
  { id: 'T7_MEAL_SANDWICH', nombre: 'T7 Meal Sandwich' },
  { id: 'T8_MEAL_SANDWICH', nombre: 'T8 Meal Sandwich' },
  { id: 'T4_MEAL_TACOS', nombre: 'T4 Meal Tacos' },
  { id: 'T5_MEAL_TACOS', nombre: 'T5 Meal Tacos' },
  { id: 'T6_MEAL_TACOS', nombre: 'T6 Meal Tacos' },
  { id: 'T7_MEAL_TACOS', nombre: 'T7 Meal Tacos' },
  { id: 'T8_MEAL_TACOS', nombre: 'T8 Meal Tacos' },
  { id: 'T4_MEAL_TACOSVEG', nombre: 'T4 Meal Veg Tacos' },
  { id: 'T5_MEAL_TACOSVEG', nombre: 'T5 Meal Veg Tacos' },
  { id: 'T6_MEAL_TACOSVEG', nombre: 'T6 Meal Veg Tacos' },
  { id: 'T7_MEAL_TACOSVEG', nombre: 'T7 Meal Veg Tacos' },
  { id: 'T8_MEAL_TACOSVEG', nombre: 'T8 Meal Veg Tacos' },
  { id: 'T4_MEAL_CURRY', nombre: 'T4 Meal Curry' },
  { id: 'T5_MEAL_CURRY', nombre: 'T5 Meal Curry' },
  { id: 'T6_MEAL_CURRY', nombre: 'T6 Meal Curry' },
  { id: 'T7_MEAL_CURRY', nombre: 'T7 Meal Curry' },
  { id: 'T8_MEAL_CURRY', nombre: 'T8 Meal Curry' },
  { id: 'T4_MEAL_CURRYVEG', nombre: 'T4 Meal Veg Curry' },
  { id: 'T5_MEAL_CURRYVEG', nombre: 'T5 Meal Veg Curry' },
  { id: 'T6_MEAL_CURRYVEG', nombre: 'T6 Meal Veg Curry' },
  { id: 'T7_MEAL_CURRYVEG', nombre: 'T7 Meal Veg Curry' },
  { id: 'T8_MEAL_CURRYVEG', nombre: 'T8 Meal Veg Curry' },
  { id: 'T4_MEAL_ROAST', nombre: 'T4 Meal Roast' },
  { id: 'T5_MEAL_ROAST', nombre: 'T5 Meal Roast' },
  { id: 'T6_MEAL_ROAST', nombre: 'T6 Meal Roast' },
  { id: 'T7_MEAL_ROAST', nombre: 'T7 Meal Roast' },
  { id: 'T8_MEAL_ROAST', nombre: 'T8 Meal Roast' },
  { id: 'T4_MEAL_ROASTVEG', nombre: 'T4 Meal Veg Roast' },
  { id: 'T5_MEAL_ROASTVEG', nombre: 'T5 Meal Veg Roast' },
  { id: 'T6_MEAL_ROASTVEG', nombre: 'T6 Meal Veg Roast' },
  { id: 'T7_MEAL_ROASTVEG', nombre: 'T7 Meal Veg Roast' },
  { id: 'T8_MEAL_ROASTVEG', nombre: 'T8 Meal Veg Roast' },
  { id: 'T4_MEAL_CAKE', nombre: 'T4 Meal Cake' },
  { id: 'T5_MEAL_CAKE', nombre: 'T5 Meal Cake' },
  { id: 'T6_MEAL_CAKE', nombre: 'T6 Meal Cake' },
  { id: 'T7_MEAL_CAKE', nombre: 'T7 Meal Cake' },
  { id: 'T8_MEAL_CAKE', nombre: 'T8 Meal Cake' },
  { id: 'T4_MEAL_CAKESPECIAL', nombre: 'T4 Meal Cake Special' },
  { id: 'T5_MEAL_CAKESPECIAL', nombre: 'T5 Meal Cake Special' },
  { id: 'T6_MEAL_CAKESPECIAL', nombre: 'T6 Meal Cake Special' },
  { id: 'T7_MEAL_CAKESPECIAL', nombre: 'T7 Meal Cake Special' },
  { id: 'T8_MEAL_CAKESPECIAL', nombre: 'T8 Meal Cake Special' },
  { id: 'T4_MEAL_STEW', nombre: 'T4 Meal Stew' },
  { id: 'T5_MEAL_STEW', nombre: 'T5 Meal Stew' },
  { id: 'T6_MEAL_STEW', nombre: 'T6 Meal Stew' },
  { id: 'T7_MEAL_STEW', nombre: 'T7 Meal Stew' },
  { id: 'T8_MEAL_STEW', nombre: 'T8 Meal Stew' },
  { id: 'T4_MEAL_STEWVEG', nombre: 'T4 Meal Veg Stew' },
  { id: 'T5_MEAL_STEWVEG', nombre: 'T5 Meal Veg Stew' },
  { id: 'T6_MEAL_STEWVEG', nombre: 'T6 Meal Veg Stew' },
  { id: 'T7_MEAL_STEWVEG', nombre: 'T7 Meal Veg Stew' },
  { id: 'T8_MEAL_STEWVEG', nombre: 'T8 Meal Veg Stew' },
  { id: 'T4_MEAL_OMELETTE', nombre: 'T4 Meal Omelette' },
  { id: 'T5_MEAL_OMELETTE', nombre: 'T5 Meal Omelette' },
  { id: 'T6_MEAL_OMELETTE', nombre: 'T6 Meal Omelette' },
  { id: 'T7_MEAL_OMELETTE', nombre: 'T7 Meal Omelette' },
  { id: 'T8_MEAL_OMELETTE', nombre: 'T8 Meal Omelette' },
  { id: 'T4_MEAL_OMELETTESPECIAL', nombre: 'T4 Meal Omelette Special' },
  { id: 'T5_MEAL_OMELETTESPECIAL', nombre: 'T5 Meal Omelette Special' },
  { id: 'T6_MEAL_OMELETTESPECIAL', nombre: 'T6 Meal Omelette Special' },
  { id: 'T7_MEAL_OMELETTESPECIAL', nombre: 'T7 Meal Omelette Special' },
  { id: 'T8_MEAL_OMELETTESPECIAL', nombre: 'T8 Meal Omelette Special' },
  { id: 'T4_MEAL_SOUP', nombre: 'T4 Meal Soup' },
  { id: 'T5_MEAL_SOUP', nombre: 'T5 Meal Soup' },
  { id: 'T6_MEAL_SOUP', nombre: 'T6 Meal Soup' },
  { id: 'T7_MEAL_SOUP', nombre: 'T7 Meal Soup' },
  { id: 'T8_MEAL_SOUP', nombre: 'T8 Meal Soup' },
  { id: 'T4_MEAL_SOUPSPECIAL', nombre: 'T4 Meal Soup Special' },
  { id: 'T5_MEAL_SOUPSPECIAL', nombre: 'T5 Meal Soup Special' },
  { id: 'T6_MEAL_SOUPSPECIAL', nombre: 'T6 Meal Soup Special' },
  { id: 'T7_MEAL_SOUPSPECIAL', nombre: 'T7 Meal Soup Special' },
  { id: 'T8_MEAL_SOUPSPECIAL', nombre: 'T8 Meal Soup Special' },
  { id: 'T4_MEAL_SALAD', nombre: 'T4 Meal Salad' },
  { id: 'T5_MEAL_SALAD', nombre: 'T5 Meal Salad' },
  { id: 'T6_MEAL_SALAD', nombre: 'T6 Meal Salad' },
  { id: 'T7_MEAL_SALAD', nombre: 'T7 Meal Salad' },
  { id: 'T8_MEAL_SALAD', nombre: 'T8 Meal Salad' },
  { id: 'T4_MEAL_SALADSPECIAL', nombre: 'T4 Meal Salad Special' },
  { id: 'T5_MEAL_SALADSPECIAL', nombre: 'T5 Meal Salad Special' },
  { id: 'T6_MEAL_SALADSPECIAL', nombre: 'T6 Meal Salad Special' },
  { id: 'T7_MEAL_SALADSPECIAL', nombre: 'T7 Meal Salad Special' },
  { id: 'T8_MEAL_SALADSPECIAL', nombre: 'T8 Meal Salad Special' },
  { id: 'T4_MEAL_PUDDING', nombre: 'T4 Meal Pudding' },
  { id: 'T5_MEAL_PUDDING', nombre: 'T5 Meal Pudding' },
  { id: 'T6_MEAL_PUDDING', nombre: 'T6 Meal Pudding' },
  { id: 'T7_MEAL_PUDDING', nombre: 'T7 Meal Pudding' },
  { id: 'T8_MEAL_PUDDING', nombre: 'T8 Meal Pudding' },
  { id: 'T4_MEAL_PUDDINGSPECIAL', nombre: 'T4 Meal Pudding Special' },
  { id: 'T5_MEAL_PUDDINGSPECIAL', nombre: 'T5 Meal Pudding Special' },
  { id: 'T6_MEAL_PUDDINGSPECIAL', nombre: 'T6 Meal Pudding Special' },
  { id: 'T7_MEAL_PUDDINGSPECIAL', nombre: 'T7 Meal Pudding Special' },
  { id: 'T8_MEAL_PUDDINGSPECIAL', nombre: 'T8 Meal Pudding Special' },
  { id: 'T4_MEAL_ROAST', nombre: 'T4 Meal Roast' },
  { id: 'T5_MEAL_ROAST', nombre: 'T5 Meal Roast' },
  { id: 'T6_MEAL_ROAST', nombre: 'T6 Meal Roast' },
  { id: 'T7_MEAL_ROAST', nombre: 'T7 Meal Roast' },
  { id: 'T8_MEAL_ROAST', nombre: 'T8 Meal Roast' },
  { id: 'T4_MEAL_ROASTSPECIAL', nombre: 'T4 Meal Roast Special' },
  { id: 'T5_MEAL_ROASTSPECIAL', nombre: 'T5 Meal Roast Special' },
  { id: 'T6_MEAL_ROASTSPECIAL', nombre: 'T6 Meal Roast Special' },
  { id: 'T7_MEAL_ROASTSPECIAL', nombre: 'T7 Meal Roast Special' },
  { id: 'T8_MEAL_ROASTSPECIAL', nombre: 'T8 Meal Roast Special' },
  { id: 'T4_MEAL_CURRY', nombre: 'T4 Meal Curry' },
  { id: 'T5_MEAL_CURRY', nombre: 'T5 Meal Curry' },
  { id: 'T6_MEAL_CURRY', nombre: 'T6 Meal Curry' },
  { id: 'T7_MEAL_CURRY', nombre: 'T7 Meal Curry' },
  { id: 'T8_MEAL_CURRY', nombre: 'T8 Meal Curry' },
  { id: 'T4_MEAL_CURRYSPECIAL', nombre: 'T4 Meal Curry Special' },
  { id: 'T5_MEAL_CURRYSPECIAL', nombre: 'T5 Meal Curry Special' },
  { id: 'T6_MEAL_CURRYSPECIAL', nombre: 'T6 Meal Curry Special' },
  { id: 'T7_MEAL_CURRYSPECIAL', nombre: 'T7 Meal Curry Special' },
  { id: 'T8_MEAL_CURRYSPECIAL', nombre: 'T8 Meal Curry Special' },
  { id: 'T4_MEAL_PIE', nombre: 'T4 Meal Pie' },
  { id: 'T5_MEAL_PIE', nombre: 'T5 Meal Pie' },
  { id: 'T6_MEAL_PIE', nombre: 'T6 Meal Pie' },
  { id: 'T7_MEAL_PIE', nombre: 'T7 Meal Pie' },
  { id: 'T8_MEAL_PIE', nombre: 'T8 Meal Pie' },
  { id: 'T4_MEAL_PIESPECIAL', nombre: 'T4 Meal Pie Special' },
  { id: 'T5_MEAL_PIESPECIAL', nombre: 'T5 Meal Pie Special' },
  { id: 'T6_MEAL_PIESPECIAL', nombre: 'T6 Meal Pie Special' },
  { id: 'T7_MEAL_PIESPECIAL', nombre: 'T7 Meal Pie Special' },
  { id: 'T8_MEAL_PIESPECIAL', nombre: 'T8 Meal Pie Special' },
  { id: 'T4_MEAL_PASTA', nombre: 'T4 Meal Pasta' },
  { id: 'T5_MEAL_PASTA', nombre: 'T5 Meal Pasta' },
  { id: 'T6_MEAL_PASTA', nombre: 'T6 Meal Pasta' },
  { id: 'T7_MEAL_PASTA', nombre: 'T7 Meal Pasta' },
  { id: 'T8_MEAL_PASTA', nombre: 'T8 Meal Pasta' },
  { id: 'T4_MEAL_PASTASPECIAL', nombre: 'T4 Meal Pasta Special' },
  { id: 'T5_MEAL_PASTASPECIAL', nombre: 'T5 Meal Pasta Special' },
  { id: 'T6_MEAL_PASTASPECIAL', nombre: 'T6 Meal Pasta Special' },
  { id: 'T7_MEAL_PASTASPECIAL', nombre: 'T7 Meal Pasta Special' },
  { id: 'T8_MEAL_PASTASPECIAL', nombre: 'T8 Meal Pasta Special' },
  { id: 'T4_MEAL_SANDWICH', nombre: 'T4 Meal Sandwich' },
  { id: 'T5_MEAL_SANDWICH', nombre: 'T5 Meal Sandwich' },
  { id: 'T6_MEAL_SANDWICH', nombre: 'T6 Meal Sandwich' },
  { id: 'T7_MEAL_SANDWICH', nombre: 'T7 Meal Sandwich' },
  { id: 'T8_MEAL_SANDWICH', nombre: 'T8 Meal Sandwich' },
  { id: 'T4_MEAL_SANDWICHSPECIAL', nombre: 'T4 Meal Sandwich Special' },
  { id: 'T5_MEAL_SANDWICHSPECIAL', nombre: 'T5 Meal Sandwich Special' },
  { id: 'T6_MEAL_SANDWICHSPECIAL', nombre: 'T6 Meal Sandwich Special' },
  { id: 'T7_MEAL_SANDWICHSPECIAL', nombre: 'T7 Meal Sandwich Special' },
  { id: 'T8_MEAL_SANDWICHSPECIAL', nombre: 'T8 Meal Sandwich Special' },
  { id: 'T4_MEAL_POTATO', nombre: 'T4 Meal Potato' },
  { id: 'T5_MEAL_POTATO', nombre: 'T5 Meal Potato' },
  { id: 'T6_MEAL_POTATO', nombre: 'T6 Meal Potato' },
  { id: 'T7_MEAL_POTATO', nombre: 'T7 Meal Potato' },
  { id: 'T8_MEAL_POTATO', nombre: 'T8 Meal Potato' },
  { id: 'T4_MEAL_POTATOSPECIAL', nombre: 'T4 Meal Potato Special' },
  { id: 'T5_MEAL_POTATOSPECIAL', nombre: 'T5 Meal Potato Special' },
  { id: 'T6_MEAL_POTATOSPECIAL', nombre: 'T6 Meal Potato Special' },
  { id: 'T7_MEAL_POTATOSPECIAL', nombre: 'T7 Meal Potato Special' },
  { id: 'T8_MEAL_POTATOSPECIAL', nombre: 'T8 Meal Potato Special' },
  { id: 'T4_MEAL_STEW', nombre: 'T4 Meal Stew' },
  { id: 'T5_MEAL_STEW', nombre: 'T5 Meal Stew' },
  { id: 'T6_MEAL_STEW', nombre: 'T6 Meal Stew' },
  { id: 'T7_MEAL_STEW', nombre: 'T7 Meal Stew' },
  { id: 'T8_MEAL_STEW', nombre: 'T8 Meal Stew' },
  { id: 'T4_MEAL_STEWSPECIAL', nombre: 'T4 Meal Stew Special' },
  { id: 'T5_MEAL_STEWSPECIAL', nombre: 'T5 Meal Stew Special' },
  { id: 'T6_MEAL_STEWSPECIAL', nombre: 'T6 Meal Stew Special' },
  { id: 'T7_MEAL_STEWSPECIAL', nombre: 'T7 Meal Stew Special' },
  { id: 'T8_MEAL_STEWSPECIAL', nombre: 'T8 Meal Stew Special' },
  { id: 'T4_MEAL_OMELETTE', nombre: 'T4 Meal Omelette' },
  { id: 'T5_MEAL_OMELETTE', nombre: 'T5 Meal Omelette' },
  { id: 'T6_MEAL_OMELETTE', nombre: 'T6 Meal Omelette' },
  { id: 'T7_MEAL_OMELETTE', nombre: 'T7 Meal Omelette' },
  { id: 'T8_MEAL_OMELETTE', nombre: 'T8 Meal Omelette' },
  { id: 'T4_MEAL_OMELETTESPECIAL', nombre: 'T4 Meal Omelette Special' },
  { id: 'T5_MEAL_OMELETTESPECIAL', nombre: 'T5 Meal Omelette Special' },
  { id: 'T6_MEAL_OMELETTESPECIAL', nombre: 'T6 Meal Omelette Special' },
  { id: 'T7_MEAL_OMELETTESPECIAL', nombre: 'T7 Meal Omelette Special' },
  { id: 'T8_MEAL_OMELETTESPECIAL', nombre: 'T8 Meal Omelette Special' },
  { id: 'T4_MEAL_SALAD', nombre: 'T4 Meal Salad' },
  { id: 'T5_MEAL_SALAD', nombre: 'T5 Meal Salad' },
  { id: 'T6_MEAL_SALAD', nombre: 'T6 Meal Salad' },
  { id: 'T7_MEAL_SALAD', nombre: 'T7 Meal Salad' },
  { id: 'T8_MEAL_SALAD', nombre: 'T8 Meal Salad' },
  { id: 'T4_MEAL_SALADSPECIAL', nombre: 'T4 Meal Salad Special' },
  { id: 'T5_MEAL_SALADSPECIAL', nombre: 'T5 Meal Salad Special' },
  { id: 'T6_MEAL_SALADSPECIAL', nombre: 'T6 Meal Salad Special' },
  { id: 'T7_MEAL_SALADSPECIAL', nombre: 'T7 Meal Salad Special' },
  { id: 'T8_MEAL_SALADSPECIAL', nombre: 'T8 Meal Salad Special' },
  { id: 'T4_MEAL_SOUP', nombre: 'T4 Meal Soup' },
  { id: 'T5_MEAL_SOUP', nombre: 'T5 Meal Soup' },
  { id: 'T6_MEAL_SOUP', nombre: 'T6 Meal Soup' },
  { id: 'T7_MEAL_SOUP', nombre: 'T7 Meal Soup' },
  { id: 'T8_MEAL_SOUP', nombre: 'T8 Meal Soup' },
  { id: 'T4_MEAL_SOUPSPECIAL', nombre: 'T4 Meal Soup Special' },
  { id: 'T5_MEAL_SOUPSPECIAL', nombre: 'T5 Meal Soup Special' },
  { id: 'T6_MEAL_SOUPSPECIAL', nombre: 'T6 Meal Soup Special' },
  { id: 'T7_MEAL_SOUPSPECIAL', nombre: 'T7 Meal Soup Special' },
  { id: 'T8_MEAL_SOUPSPECIAL', nombre: 'T8 Meal Soup Special' },
  { id: 'T4_MEAL_TACO', nombre: 'T4 Meal Taco' },
  { id: 'T5_MEAL_TACO', nombre: 'T5 Meal Taco' },
  { id: 'T6_MEAL_TACO', nombre: 'T6 Meal Taco' },
  { id: 'T7_MEAL_TACO', nombre: 'T7 Meal Taco' },
  { id: 'T8_MEAL_TACO', nombre: 'T8 Meal Taco' },
  { id: 'T4_MEAL_TACOSPECIAL', nombre: 'T4 Meal Taco Special' },
  { id: 'T5_MEAL_TACOSPECIAL', nombre: 'T5 Meal Taco Special' },
  { id: 'T6_MEAL_TACOSPECIAL', nombre: 'T6 Meal Taco Special' },
  { id: 'T7_MEAL_TACOSPECIAL', nombre: 'T7 Meal Taco Special' },
  { id: 'T8_MEAL_TACOSPECIAL', nombre: 'T8 Meal Taco Special' },
  { id: 'T4_MEAL_BEEFSTEW', nombre: 'T4 Meal Beef Stew' },
  { id: 'T5_MEAL_BEEFSTEW', nombre: 'T5 Meal Beef Stew' },
  { id: 'T6_MEAL_BEEFSTEW', nombre: 'T6 Meal Beef Stew' },
  { id: 'T7_MEAL_BEEFSTEW', nombre: 'T7 Meal Beef Stew' },
  { id: 'T8_MEAL_BEEFSTEW', nombre: 'T8 Meal Beef Stew' },
  { id: 'T4_MEAL_BEEFSTEWSPECIAL', nombre: 'T4 Meal Beef Stew Special' },
  { id: 'T5_MEAL_BEEFSTEWSPECIAL', nombre: 'T5 Meal Beef Stew Special' },
  { id: 'T6_MEAL_BEEFSTEWSPECIAL', nombre: 'T6 Meal Beef Stew Special' },
  { id: 'T7_MEAL_BEEFSTEWSPECIAL', nombre: 'T7 Meal Beef Stew Special' },
  { id: 'T8_MEAL_BEEFSTEWSPECIAL', nombre: 'T8 Meal Beef Stew Special' },
  { id: 'T4_MEAL_SANDWICH', nombre: 'T4 Meal Sandwich' },
  { id: 'T5_MEAL_SANDWICH', nombre: 'T5 Meal Sandwich' },
  { id: 'T6_MEAL_SANDWICH', nombre: 'T6 Meal Sandwich' },
  { id: 'T7_MEAL_SANDWICH', nombre: 'T7 Meal Sandwich' },
  { id: 'T8_MEAL_SANDWICH', nombre: 'T8 Meal Sandwich' },
  { id: 'T4_MEAL_SANDWICHSPECIAL', nombre: 'T4 Meal Sandwich Special' },
  { id: 'T5_MEAL_SANDWICHSPECIAL', nombre: 'T5 Meal Sandwich Special' },
  { id: 'T6_MEAL_SANDWICHSPECIAL', nombre: 'T6 Meal Sandwich Special' },
  { id: 'T7_MEAL_SANDWICHSPECIAL', nombre: 'T7 Meal Sandwich Special' },
  { id: 'T8_MEAL_SANDWICHSPECIAL', nombre: 'T8 Meal Sandwich Special' },
  { id: 'T4_MEAL_FISH', nombre: 'T4 Meal Fish' },
  { id: 'T5_MEAL_FISH', nombre: 'T5 Meal Fish' },
  { id: 'T6_MEAL_FISH', nombre: 'T6 Meal Fish' },
  { id: 'T7_MEAL_FISH', nombre: 'T7 Meal Fish' },
  { id: 'T8_MEAL_FISH', nombre: 'T8 Meal Fish' },
  { id: 'T4_MEAL_FISHSPECIAL', nombre: 'T4 Meal Fish Special' },
  { id: 'T5_MEAL_FISHSPECIAL', nombre: 'T5 Meal Fish Special' },
  { id: 'T6_MEAL_FISHSPECIAL', nombre: 'T6 Meal Fish Special' },
  { id: 'T7_MEAL_FISHSPECIAL', nombre: 'T7 Meal Fish Special' },
  { id: 'T8_MEAL_FISHSPECIAL', nombre: 'T8 Meal Fish Special' },
  { id: 'T4_MEAL_ROAST', nombre: 'T4 Meal Roast' },
  { id: 'T5_MEAL_ROAST', nombre: 'T5 Meal Roast' },
  { id: 'T6_MEAL_ROAST', nombre: 'T6 Meal Roast' },
  { id: 'T7_MEAL_ROAST', nombre: 'T7 Meal Roast' },
  { id: 'T8_MEAL_ROAST', nombre: 'T8 Meal Roast' },
  { id: 'T4_MEAL_ROASTSPECIAL', nombre: 'T4 Meal Roast Special' },
  { id: 'T5_MEAL_ROASTSPECIAL', nombre: 'T5 Meal Roast Special' },
  { id: 'T6_MEAL_ROASTSPECIAL', nombre: 'T6 Meal Roast Special' },
  { id: 'T7_MEAL_ROASTSPECIAL', nombre: 'T7 Meal Roast Special' },
  { id: 'T8_MEAL_ROASTSPECIAL', nombre: 'T8 Meal Roast Special' },
  { id: 'T4_MEAL_CURRY', nombre: 'T4 Meal Curry' },
  { id: 'T5_MEAL_CURRY', nombre: 'T5 Meal Curry' },
  { id: 'T6_MEAL_CURRY', nombre: 'T6 Meal Curry' },
  { id: 'T7_MEAL_CURRY', nombre: 'T7 Meal Curry' },
  { id: 'T8_MEAL_CURRY', nombre: 'T8 Meal Curry' },
  { id: 'T4_MEAL_CURRYSPECIAL', nombre: 'T4 Meal Curry Special' },
  { id: 'T5_MEAL_CURRYSPECIAL', nombre: 'T5 Meal Curry Special' },
  { id: 'T6_MEAL_CURRYSPECIAL', nombre: 'T6 Meal Curry Special' },
  { id: 'T7_MEAL_CURRYSPECIAL', nombre: 'T7 Meal Curry Special' },
  { id: 'T8_MEAL_CURRYSPECIAL', nombre: 'T8 Meal Curry Special' },
  { id: 'T4_MEAL_OMELETTE_AVALON', nombre: 'T4 Meal Omelette Avalon' },
  { id: 'T5_MEAL_OMELETTE_AVALON', nombre: 'T5 Meal Omelette Avalon' },
  { id: 'T6_MEAL_OMELETTE_AVALON', nombre: 'T6 Meal Omelette Avalon' },
  { id: 'T7_MEAL_OMELETTE_AVALON', nombre: 'T7 Meal Omelette Avalon' },
  { id: 'T8_MEAL_OMELETTE_AVALON', nombre: 'T8 Meal Omelette Avalon' },
  { id: 'T4_MEAL_SALAD_AVALON', nombre: 'T4 Meal Salad Avalon' },
  { id: 'T5_MEAL_SALAD_AVALON', nombre: 'T5 Meal Salad Avalon' },
  { id: 'T6_MEAL_SALAD_AVALON', nombre: 'T6 Meal Salad Avalon' },
  { id: 'T7_MEAL_SALAD_AVALON', nombre: 'T7 Meal Salad Avalon' },
  { id: 'T8_MEAL_SALAD_AVALON', nombre: 'T8 Meal Salad Avalon' },
  { id: 'T4_MEAL_SANDWICH_AVALON', nombre: 'T4 Meal Sandwich Avalon' },
  { id: 'T5_MEAL_SANDWICH_AVALON', nombre: 'T5 Meal Sandwich Avalon' },
  { id: 'T6_MEAL_SANDWICH_AVALON', nombre: 'T6 Meal Sandwich Avalon' },
  { id: 'T7_MEAL_SANDWICH_AVALON', nombre: 'T7 Meal Sandwich Avalon' },
  { id: 'T8_MEAL_SANDWICH_AVALON', nombre: 'T8 Meal Sandwich Avalon' },
  { id: 'T4_MEAL_SOUP_AVALON', nombre: 'T4 Meal Soup Avalon' },
  { id: 'T5_MEAL_SOUP_AVALON', nombre: 'T5 Meal Soup Avalon' },
  { id: 'T6_MEAL_SOUP_AVALON', nombre: 'T6 Meal Soup Avalon' },
  { id: 'T7_MEAL_SOUP_AVALON', nombre: 'T7 Meal Soup Avalon' },
  { id: 'T8_MEAL_SOUP_AVALON', nombre: 'T8 Meal Soup Avalon' },
  { id: 'T4_MEAL_STEW_AVALON', nombre: 'T4 Meal Stew Avalon' },
  { id: 'T5_MEAL_STEW_AVALON', nombre: 'T5 Meal Stew Avalon' },
  { id: 'T6_MEAL_STEW_AVALON', nombre: 'T6 Meal Stew Avalon' },
  { id: 'T7_MEAL_STEW_AVALON', nombre: 'T7 Meal Stew Avalon' },
  { id: 'T8_MEAL_STEW_AVALON', nombre: 'T8 Meal Stew Avalon' },
  { id: 'T4_MEAL_ROAST_AVALON', nombre: 'T4 Meal Roast Avalon' },
  { id: 'T5_MEAL_ROAST_AVALON', nombre: 'T5 Meal Roast Avalon' },
  { id: 'T6_MEAL_ROAST_AVALON', nombre: 'T6 Meal Roast Avalon' },
  { id: 'T7_MEAL_ROAST_AVALON', nombre: 'T7 Meal Roast Avalon' },
  { id: 'T8_MEAL_ROAST_AVALON', nombre: 'T8 Meal Roast Avalon' },
  { id: 'T4_MEAL_CURRY_AVALON', nombre: 'T4 Meal Curry Avalon' },
  { id: 'T5_MEAL_CURRY_AVALON', nombre: 'T5 Meal Curry Avalon' },
  { id: 'T6_MEAL_CURRY_AVALON', nombre: 'T6 Meal Curry Avalon' },
  { id: 'T7_MEAL_CURRY_AVALON', nombre: 'T7 Meal Curry Avalon' },
  { id: 'T8_MEAL_CURRY_AVALON', nombre: 'T8 Meal Curry Avalon' },
  { id: 'T4_MEAL_TACO_AVALON', nombre: 'T4 Meal Taco Avalon' },
  { id: 'T5_MEAL_TACO_AVALON', nombre: 'T5 Meal Taco Avalon' },
  { id: 'T6_MEAL_TACO_AVALON', nombre: 'T6 Meal Taco Avalon' },
  { id: 'T7_MEAL_TACO_AVALON', nombre: 'T7 Meal Taco Avalon' },
  { id: 'T8_MEAL_TACO_AVALON', nombre: 'T8 Meal Taco Avalon' },
  { id: 'T4_MEAL_FISH_AVALON', nombre: 'T4 Meal Fish Avalon' },
  { id: 'T5_MEAL_FISH_AVALON', nombre: 'T5 Meal Fish Avalon' },
  { id: 'T6_MEAL_FISH_AVALON', nombre: 'T6 Meal Fish Avalon' },
  { id: 'T7_MEAL_FISH_AVALON', nombre: 'T7 Meal Fish Avalon' },
  { id: 'T8_MEAL_FISH_AVALON', nombre: 'T8 Meal Fish Avalon' },
  { id: 'T4_MEAL_SALAD', nombre: 'T4 Meal Salad' },
  { id: 'T5_MEAL_SALAD', nombre: 'T5 Meal Salad' },
  { id: 'T6_MEAL_SALAD', nombre: 'T6 Meal Salad' },
  { id: 'T7_MEAL_SALAD', nombre: 'T7 Meal Salad' },
  { id: 'T8_MEAL_SALAD', nombre: 'T8 Meal Salad' },
  { id: 'T4_MEAL_SALADSPECIAL', nombre: 'T4 Meal Salad Special' },
  { id: 'T5_MEAL_SALADSPECIAL', nombre: 'T5 Meal Salad Special' },
  { id: 'T6_MEAL_SALADSPECIAL', nombre: 'T6 Meal Salad Special' },
  { id: 'T7_MEAL_SALADSPECIAL', nombre: 'T7 Meal Salad Special' },
  { id: 'T8_MEAL_SALADSPECIAL', nombre: 'T8 Meal Salad Special' },
  { id: 'T4_MEAL_TACO', nombre: 'T4 Meal Taco' },
  { id: 'T5_MEAL_TACO', nombre: 'T5 Meal Taco' },
  { id: 'T6_MEAL_TACO', nombre: 'T6 Meal Taco' },
  { id: 'T7_MEAL_TACO', nombre: 'T7 Meal Taco' },
  { id: 'T8_MEAL_TACO', nombre: 'T8 Meal Taco' },
  { id: 'T4_MEAL_TACOSPECIAL', nombre: 'T4 Meal Taco Special' },
  { id: 'T5_MEAL_TACOSPECIAL', nombre: 'T5 Meal Taco Special' },
  { id: 'T6_MEAL_TACOSPECIAL', nombre: 'T6 Meal Taco Special' },
  { id: 'T7_MEAL_TACOSPECIAL', nombre: 'T7 Meal Taco Special' },
  { id: 'T8_MEAL_TACOSPECIAL', nombre: 'T8 Meal Taco Special' },
  { id: 'T4_MEAL_CURRY', nombre: 'T4 Meal Curry' },
  { id: 'T5_MEAL_CURRY', nombre: 'T5 Meal Curry' },
  { id: 'T6_MEAL_CURRY', nombre: 'T6 Meal Curry' },
  { id: 'T7_MEAL_CURRY', nombre: 'T7 Meal Curry' },
  { id: 'T8_MEAL_CURRY', nombre: 'T8 Meal Curry' },
  { id: 'T4_MEAL_CURRYSPECIAL', nombre: 'T4 Meal Curry Special' },
  { id: 'T5_MEAL_CURRYSPECIAL', nombre: 'T5 Meal Curry Special' },
  { id: 'T6_MEAL_CURRYSPECIAL', nombre: 'T6 Meal Curry Special' },
  { id: 'T7_MEAL_CURRYSPECIAL', nombre: 'T7 Meal Curry Special' },
  { id: 'T8_MEAL_CURRYSPECIAL', nombre: 'T8 Meal Curry Special' },
  { id: 'T4_MEAL_SOUP', nombre: 'T4 Meal Soup' },
  { id: 'T5_MEAL_SOUP', nombre: 'T5 Meal Soup' },
  { id: 'T6_MEAL_SOUP', nombre: 'T6 Meal Soup' },
  { id: 'T7_MEAL_SOUP', nombre: 'T7 Meal Soup' },
  { id: 'T8_MEAL_SOUP', nombre: 'T8 Meal Soup' },
  { id: 'T4_MEAL_SOUPSPECIAL', nombre: 'T4 Meal Soup Special' },
  { id: 'T5_MEAL_SOUPSPECIAL', nombre: 'T5 Meal Soup Special' },
  { id: 'T6_MEAL_SOUPSPECIAL', nombre: 'T6 Meal Soup Special' },
  { id: 'T7_MEAL_SOUPSPECIAL', nombre: 'T7 Meal Soup Special' },
  { id: 'T8_MEAL_SOUPSPECIAL', nombre: 'T8 Meal Soup Special' },
  { id: 'T4_MEAL_STEW', nombre: 'T4 Meal Stew' },
  { id: 'T5_MEAL_STEW', nombre: 'T5 Meal Stew' },
  { id: 'T6_MEAL_STEW', nombre: 'T6 Meal Stew' },
  { id: 'T7_MEAL_STEW', nombre: 'T7 Meal Stew' },
  { id: 'T8_MEAL_STEW', nombre: 'T8 Meal Stew' },
  { id: 'T4_MEAL_STEWSPECIAL', nombre: 'T4 Meal Stew Special' },
  { id: 'T5_MEAL_STEWSPECIAL', nombre: 'T5 Meal Stew Special' },
  { id: 'T6_MEAL_STEWSPECIAL', nombre: 'T6 Meal Stew Special' },
  { id: 'T7_MEAL_STEWSPECIAL', nombre: 'T7 Meal Stew Special' },
  { id: 'T8_MEAL_STEWSPECIAL', nombre: 'T8 Meal Stew Special' },
  { id: 'T4_MEAL_ROAST', nombre: 'T4 Meal Roast' },
  { id: 'T5_MEAL_ROAST', nombre: 'T5 Meal Roast' },
  { id: 'T6_MEAL_ROAST', nombre: 'T6 Meal Roast' },
  { id: 'T7_MEAL_ROAST', nombre: 'T7 Meal Roast' },
  { id: 'T8_MEAL_ROAST', nombre: 'T8 Meal Roast' },
  { id: 'T4_MEAL_ROASTSPECIAL', nombre: 'T4 Meal Roast Special' },
  { id: 'T5_MEAL_ROASTSPECIAL', nombre: 'T5 Meal Roast Special' },
  { id: 'T6_MEAL_ROASTSPECIAL', nombre: 'T6 Meal Roast Special' },
  { id: 'T7_MEAL_ROASTSPECIAL', nombre: 'T7 Meal Roast Special' },
  { id: 'T8_MEAL_ROASTSPECIAL', nombre: 'T8 Meal Roast Special' },
  { id: 'T4_MEAL_FISH', nombre: 'T4 Meal Fish' },
  { id: 'T5_MEAL_FISH', nombre: 'T5 Meal Fish' },
  { id: 'T6_MEAL_FISH', nombre: 'T6 Meal Fish' },
  { id: 'T7_MEAL_FISH', nombre: 'T7 Meal Fish' },
  { id: 'T8_MEAL_FISH', nombre: 'T8 Meal Fish' },
  { id: 'T4_MEAL_FISHSPECIAL', nombre: 'T4 Meal Fish Special' },
  { id: 'T5_MEAL_FISHSPECIAL', nombre: 'T5 Meal Fish Special' },
  { id: 'T6_MEAL_FISHSPECIAL', nombre: 'T6 Meal Fish Special' },
  { id: 'T7_MEAL_FISHSPECIAL', nombre: 'T7 Meal Fish Special' },
  { id: 'T8_MEAL_FISHSPECIAL', nombre: 'T8 Meal Fish Special' },
  { id: 'T4_MEAL_OMELETTE', nombre: 'T4 Meal Omelette' },
  { id: 'T5_MEAL_OMELETTE', nombre: 'T5 Meal Omelette' },
  { id: 'T6_MEAL_OMELETTE', nombre: 'T6 Meal Omelette' },
  { id: 'T7_MEAL_OMELETTE', nombre: 'T7 Meal Omelette' },
  { id: 'T8_MEAL_OMELETTE', nombre: 'T8 Meal Omelette' },
  { id: 'T4_MEAL_OMELETTESPECIAL', nombre: 'T4 Meal Omelette Special' },
  { id: 'T5_MEAL_OMELETTESPECIAL', nombre: 'T5 Meal Omelette Special' },
  { id: 'T6_MEAL_OMELETTESPECIAL', nombre: 'T6 Meal Omelette Special' },
  { id: 'T7_MEAL_OMELETTESPECIAL', nombre: 'T7 Meal Omelette Special' },
  { id: 'T8_MEAL_OMELETTESPECIAL', nombre: 'T8 Meal Omelette Special' },
  { id: 'T4_MEAL_MUSHROOMSOUP', nombre: 'T4 Meal Mushroom Soup' },
  { id: 'T5_MEAL_MUSHROOMSOUP', nombre: 'T5 Meal Mushroom Soup' },
  { id: 'T6_MEAL_MUSHROOMSOUP', nombre: 'T6 Meal Mushroom Soup' },
  { id: 'T7_MEAL_MUSHROOMSOUP', nombre: 'T7 Meal Mushroom Soup' },
  { id: 'T8_MEAL_MUSHROOMSOUP', nombre: 'T8 Meal Mushroom Soup' },
  { id: 'T4_MEAL_MUSHROOMSOUPSPECIAL', nombre: 'T4 Meal Mushroom Soup Special' },
  { id: 'T5_MEAL_MUSHROOMSOUPSPECIAL', nombre: 'T5 Meal Mushroom Soup Special' },
  { id: 'T6_MEAL_MUSHROOMSOUPSPECIAL', nombre: 'T6 Meal Mushroom Soup Special' },
  { id: 'T7_MEAL_MUSHROOMSOUPSPECIAL', nombre: 'T7 Meal Mushroom Soup Special' },
  { id: 'T8_MEAL_MUSHROOMSOUPSPECIAL', nombre: 'T8 Meal Mushroom Soup Special' },
  { id: 'T4_MEAL_SANDWICH', nombre: 'T4 Meal Sandwich' },
  { id: 'T5_MEAL_SANDWICH', nombre: 'T5 Meal Sandwich' },
  { id: 'T6_MEAL_SANDWICH', nombre: 'T6 Meal Sandwich' },
  { id: 'T7_MEAL_SANDWICH', nombre: 'T7 Meal Sandwich' },
  { id: 'T8_MEAL_SANDWICH', nombre: 'T8 Meal Sandwich' },
  { id: 'T4_MEAL_SANDWICHSPECIAL', nombre: 'T4 Meal Sandwich Special' },
  { id: 'T5_MEAL_SANDWICHSPECIAL', nombre: 'T5 Meal Sandwich Special' },
  { id: 'T6_MEAL_SANDWICHSPECIAL', nombre: 'T6 Meal Sandwich Special' },
  { id: 'T7_MEAL_SANDWICHSPECIAL', nombre: 'T7 Meal Sandwich Special' },
  { id: 'T8_MEAL_SANDWICHSPECIAL', nombre: 'T8 Meal Sandwich Special' },
  { id: 'T4_MEAL_PIE', nombre: 'T4 Meal Pie' },
  { id: 'T5_MEAL_PIE', nombre: 'T5 Meal Pie' },
  { id: 'T6_MEAL_PIE', nombre: 'T6 Meal Pie' },
  { id: 'T7_MEAL_PIE', nombre: 'T7 Meal Pie' },
  { id: 'T8_MEAL_PIE', nombre: 'T8 Meal Pie' },
  { id: 'T4_MEAL_PIESPECIAL', nombre: 'T4 Meal Pie Special' },
  { id: 'T5_MEAL_PIESPECIAL', nombre: 'T5 Meal Pie Special' },
  { id: 'T6_MEAL_PIESPECIAL', nombre: 'T6 Meal Pie Special' },
  { id: 'T7_MEAL_PIESPECIAL', nombre: 'T7 Meal Pie Special' },
  { id: 'T8_MEAL_PIESPECIAL', nombre: 'T8 Meal Pie Special' }
  
];
  export default itemsSeleccionados;

